### ISSUE TITLE
Investigate the failure of test_master_file_status_update_ok unit test

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#24421]
## Description

In the last two bump revisions of 4.8.1 the test `test_master_file_status_update_ok` failed.

<details><summary>Test output</summary>
<p>

```bash
wazuh/core/cluster/tests/test_master.py::test_master_file_status_update_ok FAILED [ 15%]
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 182, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_result.py", line 100, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 182, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_result.py", line 100, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/runner.py", line 114, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/runner.py", line 133, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/runner.py", line 228, in call_and_report
INTERNALERROR>     hook.pytest_exception_interact(node=item, call=call, report=report)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pytest_trio/plugin.py", line 62, in pytest_exception_interact
INTERNALERROR>     if issubclass(call.excinfo.type, trio.MultiError):
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/trio/_deprecate.py", line 153, in __getattr__
INTERNALERROR>     raise AttributeError(msg.format(self.__name__, name))
INTERNALERROR> AttributeError: module 'trio' has no attribute 'MultiError'
```

</p>
</details> 

* https://github.com/wazuh/wazuh/pull/24389/checks?check_run_id=26931191747
* https://github.com/wazuh/wazuh/pull/24420/checks?check_run_id=27057545892

Since #21678 was merged into 4.9.0 we can't see the real reason for failure.

Running the complete suite locally all tests pass.

<details><summary>Local execution</summary>
<p>

```python
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-7.3.1, pluggy-1.5.0
rootdir: /home/nstefani/git/wazuh/framework
configfile: pytest.ini
plugins: aiohttp-1.0.4, asyncio-0.18.1, tavern-1.23.5, trio-0.7.0, html-2.1.1, metadata-3.1.1
asyncio: mode=auto
collected 2225 items

framework/scripts/tests/test_agent_groups.py ..............              [  0%]
framework/scripts/tests/test_agent_upgrade.py .................          [  1%]
framework/scripts/tests/test_cluster_control.py ......                   [  1%]
framework/scripts/tests/test_rbac_control.py .........                   [  2%]
framework/scripts/tests/test_wazuh_clusterd.py .......                   [  2%]
framework/scripts/tests/test_wazuh_logtest.py ......................     [  3%]
framework/wazuh/core/cluster/dapi/tests/test_dapi.py ................... [  4%]
.............                                                            [  4%]
framework/wazuh/core/cluster/tests/test_client.py ................       [  5%]
framework/wazuh/core/cluster/tests/test_cluster.py ..................... [  6%]
..............                                                           [  7%]
framework/wazuh/core/cluster/tests/test_common.py ...................... [  8%]
................................................................         [ 10%]
framework/wazuh/core/cluster/tests/test_control.py ......                [ 11%]
framework/wazuh/core/cluster/tests/test_local_client.py ..............   [ 11%]
framework/wazuh/core/cluster/tests/test_local_server.py ................ [ 12%]
........                                                                 [ 12%]
framework/wazuh/core/cluster/tests/test_master.py ...................... [ 13%]
..........................                                               [ 15%]
framework/wazuh/core/cluster/tests/test_server.py ...................... [ 16%]
.......                                                                  [ 16%]
framework/wazuh/core/cluster/tests/test_utils.py ....................... [ 17%]
.                                                                        [ 17%]
framework/wazuh/core/cluster/tests/test_worker.py ...................... [ 18%]
............                                                             [ 19%]
framework/wazuh/core/tests/test_active_response.py ....................  [ 19%]
framework/wazuh/core/tests/test_agent.py ............................... [ 21%]
........................................................................ [ 24%]
..............................................                           [ 26%]
framework/wazuh/core/tests/test_cdb_list.py ............................ [ 27%]
..........                                                               [ 28%]
framework/wazuh/core/tests/test_common.py .........                      [ 28%]
framework/wazuh/core/tests/test_configuration.py ....................... [ 29%]
.................................................................        [ 32%]
framework/wazuh/core/tests/test_database.py .............                [ 33%]
framework/wazuh/core/tests/test_decoder.py ................              [ 33%]
framework/wazuh/core/tests/test_exception.py ..........                  [ 34%]
framework/wazuh/core/tests/test_input_validator.py ...                   [ 34%]
framework/wazuh/core/tests/test_logtest.py ..                            [ 34%]
framework/wazuh/core/tests/test_manager.py ............................. [ 35%]
..                                                                       [ 36%]
framework/wazuh/core/tests/test_mitre.py .............                   [ 36%]
framework/wazuh/core/tests/test_pyDaemonModule.py .....                  [ 36%]
framework/wazuh/core/tests/test_results.py ............................. [ 38%]
...........                                                              [ 38%]
framework/wazuh/core/tests/test_rootcheck.py .............               [ 39%]
framework/wazuh/core/tests/test_rule.py .......................          [ 40%]
framework/wazuh/core/tests/test_sca.py .............................     [ 41%]
framework/wazuh/core/tests/test_security.py .............                [ 42%]
framework/wazuh/core/tests/test_stats.py .................               [ 42%]
framework/wazuh/core/tests/test_syscheck.py .......                      [ 43%]
framework/wazuh/core/tests/test_syscollector.py ...                      [ 43%]
framework/wazuh/core/tests/test_task.py ........                         [ 43%]
framework/wazuh/core/tests/test_utils.py ............................... [ 45%]
........................................................................ [ 48%]
........................................................................ [ 51%]
........................................................................ [ 54%]
..............................................                           [ 56%]
framework/wazuh/core/tests/test_wazuh_queue.py .......................   [ 57%]
framework/wazuh/core/tests/test_wazuh_socket.py ....................     [ 58%]
framework/wazuh/core/tests/test_wdb.py ...............................   [ 60%]
framework/wazuh/core/tests/test_wlogging.py ............                 [ 60%]
framework/wazuh/rbac/tests/test_auth_context.py ..                       [ 60%]
framework/wazuh/rbac/tests/test_decorators.py .......................... [ 62%]
........................................................................ [ 65%]
...........                                                              [ 65%]
framework/wazuh/rbac/tests/test_default_configuration.py ............... [ 66%]
........................................                                 [ 68%]
framework/wazuh/rbac/tests/test_orm.py ................................. [ 69%]
.............................                                            [ 71%]
framework/wazuh/rbac/tests/test_preprocessor.py ...........              [ 71%]
framework/wazuh/tests/test_active_response.py ............               [ 72%]
framework/wazuh/tests/test_agent.py .................................... [ 73%]
........................................................................ [ 76%]
..............                                                           [ 77%]
framework/wazuh/tests/test_cdb_list.py ................................. [ 79%]
....................                                                     [ 79%]
framework/wazuh/tests/test_ciscat.py .................................   [ 81%]
framework/wazuh/tests/test_cluster.py ..........                         [ 81%]
framework/wazuh/tests/test_decoder.py .................................. [ 83%]
........................                                                 [ 84%]
framework/wazuh/tests/test_event.py ....                                 [ 84%]
framework/wazuh/tests/test_group.py .......                              [ 84%]
framework/wazuh/tests/test_logtest.py ......                             [ 85%]
framework/wazuh/tests/test_manager.py .................................. [ 86%]
..                                                                       [ 86%]
framework/wazuh/tests/test_mitre.py .......                              [ 87%]
framework/wazuh/tests/test_rootcheck.py ................................ [ 88%]
..................                                                       [ 89%]
framework/wazuh/tests/test_rule.py ..................................... [ 91%]
.....................................                                    [ 92%]
framework/wazuh/tests/test_sca.py ...........                            [ 93%]
framework/wazuh/tests/test_security.py ................................. [ 94%]
......................................                                   [ 96%]
framework/wazuh/tests/test_stats.py ...............                      [ 97%]
framework/wazuh/tests/test_syscheck.py .........................         [ 98%]
framework/wazuh/tests/test_syscollector.py ............                  [ 98%]
framework/wazuh/tests/test_task.py ............................          [100%]

======================= 2225 passed in 264.16s (0:04:24) =======================

```

</p>
</details> 

So, It is necessary to investigate and find the root cause of the failing test.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by javiersanchz** [comment]
## Update

Create a new environment to also test running the entire test suite with the `requirements-dev.txt` we have in `4.8.1`, and as observed in the issue description, all tests passed successfully:

<details>

<summary>Tests</summary>

```
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.5.0
rootdir: /home/wazuh/Git/wazuh/framework
configfile: pytest.ini
plugins: aiohttp-1.0.4, metadata-3.1.1, html-2.1.1, trio-0.7.0, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 2225 items                                                                                                                                                                                              

framework/scripts/tests/test_agent_groups.py ..............                                                                                                                                                 [  0%]
framework/scripts/tests/test_agent_upgrade.py .................                                                                                                                                             [  1%]
framework/scripts/tests/test_cluster_control.py ......                                                                                                                                                      [  1%]
framework/scripts/tests/test_rbac_control.py .........                                                                                                                                                      [  2%]
framework/scripts/tests/test_wazuh_clusterd.py .......                                                                                                                                                      [  2%]
framework/scripts/tests/test_wazuh_logtest.py ......................                                                                                                                                        [  3%]
framework/wazuh/core/cluster/dapi/tests/test_dapi.py ................................                                                                                                                       [  4%]
framework/wazuh/core/cluster/tests/test_client.py ................                                                                                                                                          [  5%]
framework/wazuh/core/cluster/tests/test_cluster.py ...................................                                                                                                                      [  7%]
framework/wazuh/core/cluster/tests/test_common.py ......................................................................................                                                                    [ 10%]
framework/wazuh/core/cluster/tests/test_control.py ......                                                                                                                                                   [ 11%]
framework/wazuh/core/cluster/tests/test_local_client.py ..............                                                                                                                                      [ 11%]
framework/wazuh/core/cluster/tests/test_local_server.py ........................                                                                                                                            [ 12%]
framework/wazuh/core/cluster/tests/test_master.py ................................................                                                                                                          [ 15%]
framework/wazuh/core/cluster/tests/test_server.py .............................                                                                                                                             [ 16%]
framework/wazuh/core/cluster/tests/test_utils.py ........................                                                                                                                                   [ 17%]
framework/wazuh/core/cluster/tests/test_worker.py ..................................                                                                                                                        [ 19%]
framework/wazuh/core/tests/test_active_response.py ....................                                                                                                                                     [ 19%]
framework/wazuh/core/tests/test_agent.py .....................................................................................................................................................              [ 26%]
framework/wazuh/core/tests/test_cdb_list.py ......................................                                                                                                                          [ 28%]
framework/wazuh/core/tests/test_common.py .........                                                                                                                                                         [ 28%]
framework/wazuh/core/tests/test_configuration.py ........................................................................................                                                                   [ 32%]
framework/wazuh/core/tests/test_database.py .............                                                                                                                                                   [ 33%]
framework/wazuh/core/tests/test_decoder.py ................                                                                                                                                                 [ 33%]
framework/wazuh/core/tests/test_exception.py ..........                                                                                                                                                     [ 34%]
framework/wazuh/core/tests/test_input_validator.py ...                                                                                                                                                      [ 34%]
framework/wazuh/core/tests/test_logtest.py ..                                                                                                                                                               [ 34%]
framework/wazuh/core/tests/test_manager.py ...............................                                                                                                                                  [ 36%]
framework/wazuh/core/tests/test_mitre.py .............                                                                                                                                                      [ 36%]
framework/wazuh/core/tests/test_pyDaemonModule.py .....                                                                                                                                                     [ 36%]
framework/wazuh/core/tests/test_results.py ........................................                                                                                                                         [ 38%]
framework/wazuh/core/tests/test_rootcheck.py .............                                                                                                                                                  [ 39%]
framework/wazuh/core/tests/test_rule.py .......................                                                                                                                                             [ 40%]
framework/wazuh/core/tests/test_sca.py .............................                                                                                                                                        [ 41%]
framework/wazuh/core/tests/test_security.py .............                                                                                                                                                   [ 42%]
framework/wazuh/core/tests/test_stats.py .................                                                                                                                                                  [ 42%]
framework/wazuh/core/tests/test_syscheck.py .......                                                                                                                                                         [ 43%]
framework/wazuh/core/tests/test_syscollector.py ...                                                                                                                                                         [ 43%]
framework/wazuh/core/tests/test_task.py ........                                                                                                                                                            [ 43%]
framework/wazuh/core/tests/test_utils.py .................................................................................................................................................................. [ 51%]
...................................................................................................................................                                                                         [ 56%]
framework/wazuh/core/tests/test_wazuh_queue.py .......................                                                                                                                                      [ 57%]
framework/wazuh/core/tests/test_wazuh_socket.py ....................                                                                                                                                        [ 58%]
framework/wazuh/core/tests/test_wdb.py ...............................                                                                                                                                      [ 60%]
framework/wazuh/core/tests/test_wlogging.py ............                                                                                                                                                    [ 60%]
framework/wazuh/rbac/tests/test_auth_context.py ..                                                                                                                                                          [ 60%]
framework/wazuh/rbac/tests/test_decorators.py .............................................................................................................                                                 [ 65%]
framework/wazuh/rbac/tests/test_default_configuration.py .......................................................                                                                                            [ 68%]
framework/wazuh/rbac/tests/test_orm.py ..............................................................                                                                                                       [ 71%]
framework/wazuh/rbac/tests/test_preprocessor.py ...........                                                                                                                                                 [ 71%]
framework/wazuh/tests/test_active_response.py ............                                                                                                                                                  [ 72%]
framework/wazuh/tests/test_agent.py ..........................................................................................................................                                              [ 77%]
framework/wazuh/tests/test_cdb_list.py .....................................................                                                                                                                [ 79%]
framework/wazuh/tests/test_ciscat.py .................................                                                                                                                                      [ 81%]
framework/wazuh/tests/test_cluster.py ..........                                                                                                                                                            [ 81%]
framework/wazuh/tests/test_decoder.py ..........................................................                                                                                                            [ 84%]
framework/wazuh/tests/test_event.py ....                                                                                                                                                                    [ 84%]
framework/wazuh/tests/test_group.py .......                                                                                                                                                                 [ 84%]
framework/wazuh/tests/test_logtest.py ......                                                                                                                                                                [ 85%]
framework/wazuh/tests/test_manager.py ....................................                                                                                                                                  [ 86%]
framework/wazuh/tests/test_mitre.py .......                                                                                                                                                                 [ 87%]
framework/wazuh/tests/test_rootcheck.py ..................................................                                                                                                                  [ 89%]
framework/wazuh/tests/test_rule.py ..........................................................................                                                                                               [ 92%]
framework/wazuh/tests/test_sca.py ...........                                                                                                                                                               [ 93%]
framework/wazuh/tests/test_security.py .......................................................................                                                                                              [ 96%]
framework/wazuh/tests/test_stats.py ...............                                                                                                                                                         [ 97%]
framework/wazuh/tests/test_syscheck.py .........................                                                                                                                                            [ 98%]
framework/wazuh/tests/test_syscollector.py ............                                                                                                                                                     [ 98%]
framework/wazuh/tests/test_task.py ............................                                                                                                                                             [100%]

======================================================================================== 2225 passed in 216.57s (0:03:36) =========================================================================================
```

</details>

- It seems that when installing requirements-dev.txt in the environment, it installs `pytest-trio==0.7.0`, which is the current version in `4.8.1`, but it also installs `trio==0.24.0`, which may be causing the compatibility issue.

- I ran the same tests with `pytest-trio==0.8.0`, and all tests passed as well.

- Since I can't reproduce the `INTERNALERROR` locally, I'm going to create a test branch with `pytest-trio==0.8.0` and open a PR to run local checks to see if this resolves the issue, similar to what was done in https://github.com/wazuh/wazuh/issues/21678

**Comment by javiersanchz** [comment]
## Update

According to the `pytest-trio` repository, its version `0.7.0` should be compatible with `trio >= 0.15.0`.

https://github.com/python-trio/pytest-trio/blob/v0.7.0/docs-requirements.in

**Comment by javiersanchz** [comment]
## Update

t seems the reason for these errors has been found
Inside https://trio.readthedocs.io/en/stable/reference-core.html it is explained

![image](https://github.com/wazuh/wazuh/assets/96108386/cb86b927-d9e7-4f9d-b736-7329b122f9b2)

- The text discusses the historical use and subsequent disuse of Trio's MultiError in favor of ExceptionGroups. Initially, Trio lacked structured concurrency or a standardized exception handling mechanism, which led to issues where some APIs generated individual exceptions, while Trio.MultiError consolidated concurrent exceptions only if there were more than one. This approach proved problematic as it caused failures under heavier loads due to incomplete handling in the calling code.

- To address this, Trio adopted ExceptionGroups (similar to asyncio.TaskGroup) to uniformly handle errors, ensuring robustness across different scenarios. Starting from Trio 0.25, ExceptionGroups became the default behavior, completely replacing MultiError

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

The error message indicates that `pytest_trio` is trying to access `trio.MultiError`, but this attribute no longer exists in the current version of `trio` that you are using

`INTERNALERROR> AttributeError: module 'trio' has no attribute 'MultiError'
`

Upgrading to `pytest_trio 0.8.0` should solve this problem.

**Comment by javiersanchz** [comment]
## Update

After changing the version, we can see that all checks passed and the failed tests in https://github.com/wazuh/wazuh/pull/24389/checks?check_run_id=26931191747 and https://github.com/wazuh/wazuh/pull/24420/checks?check_run_id=27057545892 passed correctly.
