### PR TITLE
Use posix-flavour MinGW C compiler for the winagent CMake build

### LINKED ISSUE #38580: winagent: libhttps_client.dll fails to link (undefined std::thread/condition_variable) since PR #38394's zstd vendoring
### Description

`TARGET=winagent` fails to link `libhttps_client.dll` with undefined references to
`std::thread`/`std::condition_variable` symbols, on the exact same toolchain/image that
built it successfully 12 days earlier. This is a regression from a specific merged commit,
not a toolchain or environment difference — see evidence below.

### Error

```
/usr/bin/i686-w64-mingw32-ld: CMakeFiles/https_client.dir/objects.a(callbackDispatcher.cpp.obj):/usr/lib/gcc/i686-w64-mingw32/10-posix/include/c++/condition_variable:111: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)'
/wazuh-local-src/src/client-agent/https_client/src/callbackDispatcher.cpp:15: undefined reference to `std::condition_variable::condition_variable()'
undefined reference to `std::thread::_M_start_thread(...)'
undefined reference to `std::thread::join()'
... (same pattern across controlStream.cpp, curlHandle.cpp, stopToken.hpp, registrationGate.hpp)
```

Reproduced via `.github/workflows/5_builderpackage_externals.yml`'s `Smoke build
(winagent-i686)` job — [failing run](https://github.com/wazuh/wazuh/actions/runs/32852582766/job/97823341067) vs. the [same job succeeding 12 days earlier](https://github.com/wazuh/wazuh/actions/runs/31626022027/job/94217947673).

### Root cause

Bisected by ruling out every environment variable between the two runs above, in order:

1. **Docker image**: both pulled `ghcr.io/wazuh/compile_windows_agent:5.0.0` at the exact
   same digest, `sha256:ab69c887305132dac8253239e1af28385744bbfbae796080593e7935a114f998`.
   Byte-identical.
2. **CMake configure command**: identical in both logs, including
   `-DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++-posix`.
3. **Build parallelism**: `JOBS=8` in both.

With image, toolchain invocation, and parallelism all ruled out, the only remaining
difference is the source tree itself. Diffing `src/client-agent/https_client/CMakeLists.txt`
between the two commits shows:

```diff
-add_library(https_client SHARED ${HTTPS_CLIENT_SRC} ${RESOURCE_OBJ_DLL})
+add_library(https_client SHARED ${HTTPS_CLIENT_SRC}
+            ${SRC_FOLDER}/shared/src/os_cert_bundle.c ${RESOURCE_OBJ_DLL})
...
-target_link_libraries(https_client PRIVATE wazuhext pthread)
+target_link_libraries(https_client PRIVATE wazuhext pthread ext_zstd)
...
 if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
   set_target_properties(
     https_client PROPERTIES LINK_FLAGS
-                            "-Wl,--add-stdcall-alias -Wl,--output-def,libhttps_client.def")
+                            "-Wl,--add-stdcall-alias -Wl,--exclude-libs,libzstd.a -Wl,--output-def,libhttps_client.def")
```

That change is commit `31e0e652507` ("feat(https_client): vendor zstd for the
winagent build"), introduced by **PR #38355** ("Enhancement/38308 agent https zstd
compression", base `5.0.0-https`), merged **2026-08-14 02:12 UTC**. It reached `5.0.0`
itself the same day via **PR #38394** ("Introduce HTTPS-based agent-manager communication
protocol", 19:33 UTC), the merge of the long-lived `5.0.0-https` integration branch — #38394
is why it's on `5.0.0` at all, but #38355 is where the actual change was written and
reviewed (as commit `201682ee6c8` after the integration-branch rebase). Both merges landed
the day after the last known-good run above.

Adding `ext_zstd` (a plain `STATIC IMPORTED` target,
`add_library(ext_zstd STATIC IMPORTED GLOBAL)` in `src/external/CMakeLists.txt`) to the
Windows link line, together with the new `-Wl,--exclude-libs,libzstd.a` flag, changes the
final link command for `libhttps_client.dll` in a way that now leaves
`std::thread`/`std::condition_variable` unresolved — even though nothing about the
toolchain or headers used to compile those translation units changed. I have not yet
isolated the exact linker-internals mechanism (e.g. whether it's a link-order effect from
inserting a static archive before libstdc++/libwinpthread would otherwise be picked up
implicitly, or an interaction with `--exclude-libs`); that would need an isolated toggle
build (same image, with vs. without just that CMakeLists.txt change) to confirm.

### Impact

Blocks `TARGET=winagent` builds that go through this smoke-build path. Worth checking
whether this also affects the packaged Windows agent build/release pipeline, since both
consume the same `https_client` CMake target.

### Suggested next step

Bisect with an isolated toggle (same `compile_windows_agent:5.0.0` image, same cmake
invocation, only the `ext_zstd` link line / `--exclude-libs` flag differing) to pin down the
exact mechanism, then fix (likely: explicit `-lstdc++ -lwinpthread` / link-order adjustment
for the Windows leg of this target, or reordering `ext_zstd` relative to the implicit
default libraries).

### PR DESCRIPTION
**Pull request by Miguevrgo**
## Description

`TARGET=winagent` fails to link `libhttps_client.dll` with undefined references to
`std::thread` / `std::condition_variable` / `std::call_once` symbols.

The cause is a MinGW thread-model flavour mismatch in `src/Makefile:101`, which configured
CMake with the **win32**-flavour C compiler and the **posix**-flavour C++ compiler:

```make
CC=gcc          # -> i686-w64-mingw32-gcc        (win32 flavour, the Debian default)
CXX=g++-posix   # -> i686-w64-mingw32-g++-posix  (posix flavour)
```

Both flavours are installed side by side in the `compile_windows_agent` image, and only the
posix one has a threading-capable libstdc++ (the win32 one is built without
`_GLIBCXX_HAS_GTHREADS`, so `std::thread`, `std::condition_variable` and the `std::call_once`
machinery are absent from the archive entirely):

```
$ i686-w64-mingw32-nm -g /usr/lib/gcc/i686-w64-mingw32/10-win32/libstdc++.a | grep -c _M_start_thread
0
$ i686-w64-mingw32-nm -g /usr/lib/gcc/i686-w64-mingw32/10-posix/libstdc++.a | grep -c _M_start_thread
3
```

For a target whose sources are **all C++** the mismatch is invisible: CMake links with
`CMAKE_CXX_COMPILER` and the driver finds its own posix libstdc++. For a target that **mixes C
and C++ sources**, CMake additionally appends the C compiler's implicit link directory to the
link line, so the win32 directory lands ahead of the `g++-posix` driver's own search path and
its implicit `-lstdc++` resolves to the wrong libstdc++:

```
$ cat src/build/client-agent/https_client/CMakeFiles/https_client.dir/linklibs.rsp
 -L/wazuh-local-src/src  -L/wazuh-local-src/src/build/lib  -L/usr/lib/gcc/i686-w64-mingw32/10-win32  ...
```

`https_client` became such a mixed-language target when
`src/client-agent/https_client/CMakeLists.txt:22` started compiling
`shared/src/os_cert_bundle.c` directly into the previously all-C++ library. That is what
exposed the latent flavour mismatch; nothing about `os_cert_bundle.c` itself is wrong.

The `ext_zstd` link entry and the `-Wl,--exclude-libs,libzstd.a` flag added by the same
change were ruled out: reproduced in isolation in the same image (`sha256:ab69c887...`), a
DLL using `std::thread` links cleanly both with and without them. The minimal reproducer is a
`SHARED` target with one `.cpp` using `std::thread` plus one `.c` file, configured with
`-DCMAKE_C_COMPILER=i686-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++-posix`:
it fails, and dropping the `.c` file makes it link.

The same latent bug affects any other winagent CMake target mixing C and C++ that uses those
libstdc++ threading symbols. The existing mixed targets (`fimdb`, `sysinfo`,
`agent_sync_protocol`) only use header-inline C++ threading facilities, which is why
`https_client` was the first to break.

Closes #38580

## Proposed Changes

One line in `src/Makefile`: configure CMake with the posix-flavour C compiler so the C and C++
toolchains use the same MinGW thread model.

```diff
-CMAKE_OPTS=... -DCMAKE_C_COMPILER=${MING_BASE}${CC} -DCMAKE_CXX_COMPILER=${MING_BASE}${CXX} ...
+CMAKE_OPTS=... -DCMAKE_C_COMPILER=${MING_BASE}gcc-posix -DCMAKE_CXX_COMPILER=${MING_BASE}${CXX} ...
```

`${CC}` is left untouched so the `MING_BASE` cross-prefix detection below it (which keys off
`ifeq (${CC}, gcc)`) keeps working, matching how `${CXX}` already hardcodes `g++-posix`.

With both flavours aligned, the C implicit link directory equals the C++ one and CMake drops
the redundant `-L` from the link line altogether.

`ext_zstd` and `-Wl,--exclude-libs,libzstd.a` are intentionally left as they are.

### Results and Evidence

Both runs: `make TARGET=winagent -j$(nproc)` inside
`ghcr.io/wazuh/compile_windows_agent:5.0.0`, image digest
`sha256:ab69c887305132dac8253239e1af28385744bbfbae796080593e7935a114f998` (the same digest as
the failing CI runs), against precompiled deps from `make deps TARGET=winagent`.

**Before** (branch point, `28289c3682`):

```
[ 42%] Linking CXX shared library ../../bin/libhttps_client.dll
/usr/bin/i686-w64-mingw32-ld: /usr/lib/gcc/i686-w64-mingw32/10-posix/include/c++/thread:149: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())'
/usr/bin/i686-w64-mingw32-ld: CMakeFiles/https_client.dir/objects.a(httpsClientFacade.cpp.obj): in function `ZN6Waiter11requestStopEv':
/wazuh-local-src/src/client-agent/https_client/src/stopToken.hpp:63: undefined reference to `std::condition_variable::notify_all()'
collect2: error: ld returned 1 exit status
make[4]: *** [client-agent/https_client/CMakeFiles/https_client.dir/build.make:559: bin/libhttps_client.dll] Error 1
make: *** [Makefile:360: winagent] Error 2
```

Link line for that build:

```
linklibs.rsp:  -L/wazuh-local-src/src  -L/wazuh-local-src/src/build/lib  -L/usr/lib/gcc/i686-w64-mingw32/10-win32  ../../external/libwazuhext.dll.a -lpthread .../libzstd.a -lkernel32 ...
```

**After** (this branch, clean `src/build`):

```
[ 42%] Linking CXX shared library ../../bin/libhttps_client.dll
Generating libhttps_client.lib import library
[ 42%] Built target https_client
...
Done building winagent
```

Link line after the fix, with the win32 directory gone:

```
linklibs.rsp:  -L/wazuh-local-src/src  -L/wazuh-local-src/src/build/lib  ../../external/libwazuhext.dll.a -lpthread .../libzstd.a -lkernel32 ...
```

Artifacts produced:

```
-rwxr-xr-x 1 18152895 src/build/bin/libhttps_client.dll
-rw-r--r-- 1   614026 src/build/bin/libhttps_client.lib
```

The full winagent build completes with exit status 0 and zero undefined references. Pre-existing
compiler warnings (e.g. `loggerHelper.h:374: visibility attribute not supported in this
configuration`) are unchanged by this PR, so the "without warnings" box is left unchecked.

### Manual tests with their corresponding evidence

- Compilation without warnings on every supported platform
  - [ ] Linux
  - [ ] Windows
  - [ ] MAC OS X
- [ ] Log syntax and correct language review

- Memory tests for Linux
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Coverity
  - [ ] UMDH
- Memory tests for macOS
  - [ ] Leaks
  - [ ] AddressSanitizer

- Decoder/Rule tests _(Wazuh v4.x)_
  - [ ] Added unit testing files ".ini"
  - [ ] `runtests.py` executed without errors

- Engine _(Wazuh v5.x and above)_
  - [ ] Test run in parallel
  - [ ] ASAN for test (utest/ctest)
  - [ ] TSAN for test and wazuh-engine.

- Wazuh server API/Framework
  - [ ] Run API Integration Tests

### Artifacts Affected

Every artifact of the `TARGET=winagent` CMake build, since the C compiler used to configure it
changes flavour. `libhttps_client.dll` / `libhttps_client.lib` go from failing to link to
building. Both consumers of the target are unblocked: the
`5_builderpackage_externals.yml` "Smoke build (winagent-i686)" job and the
`wazuh-agent-packages` "5.X - Build Wazuh agent Windows" pipeline.

No source, ABI or runtime dependency change: the shipped `libstdc++-6.dll` and
`libgcc_s_dw2-1.dll` are already the posix-flavour ones (`src/Makefile:23-26` resolves them
through `i686-w64-mingw32-g++-posix --print-file-name`), so this only stops C objects from
dragging the win32 flavour into the link.

### Configuration Changes

N/A

### Tests Introduced

N/A. The regression is a build-configuration defect with no runtime surface; the existing
winagent build jobs are the test.

## Review Checklist

- [ ] Code changes reviewed
- [ ] Relevant evidence provided
- [ ] Tests cover the new functionality
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [ ] Meets requirements and/or definition of done
- [ ] No unresolved dependencies with other issues

### CODE REVIEW

**Comment by Miguevrgo** [comment]
## Evidence: Windows package generation

Windows agent package built from this branch through the release pipeline that the issue reported as broken (`wazuh/wazuh-agent-packages`, workflow "5.X - Build Wazuh agent Windows", `trust_verification=0`, `revision=0`).

- Run: https://github.com/wazuh/wazuh-agent-packages/actions/runs/33068300950
- `source_reference`: `fix/38580-winagent-libhttps_clientdll-fails-to-link-undefined-stdthreadcondition_variable-since-pr-38394s-zstd-vendoring` (commit `1c5e0d0`)
- Result: **success** (`Build Windows wazuh-agent = success`)

CMake configured with both toolchains on the same MinGW thread-model flavour, and `IMAGE_TRUST_CHECKS=0` as requested:

```
+ TRUST_VERIFICATION=0
+ FLAGS='-j 4 IMAGE_TRUST_CHECKS=0 CA_NAME="DigiCert Assured ID Root CA" '
mkdir -p build && cd build && cmake .. -DTARGET=winagent -DCMAKE_SYSTEM_NAME=Windows \
  -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc-posix -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++-posix \
  -DEVENTCHANNEL_SUPPORT=ON -DCA_NAME='DigiCert Assured ID Root CA' -DIMAGE_TRUST_CHECKS=0 \
  -DCMAKE_SYMBOLS_IN_RELEASE=ON && make
```

The target that used to fail now links:

```
[ 46%] Linking CXX shared library ../../bin/libhttps_client.dll
Generating libhttps_client.lib import library
[ 46%] Built target https_client
```

Build completes and the MSI is generated, installed and upgrade-tested on the Windows runner:

```
    IMAGE_TRUST_CHECKS: 0
    CA_NAME:            DigiCert Assured ID Root CA
Done building winagent
...
MSI_NAME = wazuh-agent_5.0.0-0_windows_1c5e0d0.msi
...
The Wazuh service was started successfully.
All checks passed successfully. Upgrade completed!
```

Artifact: `s3://xdrsiem-packages-dev-internal/development/wazuh/5.x/main/packages/wazuh-agent_5.0.0-0_windows_1c5e0d0.msi`

For reference, the same pipeline on `5.0.0` before this fix: https://github.com/wazuh/wazuh-agent-packages/actions/runs/33046668688/job/98432168515

### Note on the first pushed revision

The initial commit hardcoded `-DCMAKE_C_COMPILER=${MING_BASE}gcc-posix`, which broke the `scan-build-ubuntu-mingw-windows` job: `scan-build` overrides `CC`/`CXX` with its analyzer wrappers, which also makes `MING_BASE` empty (its detection keys off `ifeq (${CC}, gcc)`), so CMake got a bare `gcc-posix`:

```
CMake Error at CMakeLists.txt:17 (project):
  The CMAKE_C_COMPILER: gcc-posix is not a full path and was not found in the PATH.
```

The pushed version only appends the flavour suffix when `CC` is the untouched default, so an overridden `CC` is passed through verbatim:

```
$ make TARGET=winagent -n build_wazuh_cmake            # normal build
cmake .. ... -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc-posix -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++-posix ...

$ make TARGET=winagent CC=.../ccc-analyzer CXX=.../c++-analyzer -n build_wazuh_cmake
cmake .. ... -DCMAKE_C_COMPILER=/usr/share/clang/scan-build-14/libexec/ccc-analyzer -DCMAKE_CXX_COMPILER=/usr/share/clang/scan-build-14/libexec/c++-analyzer ...
```

**Review by MarcelKemp — APPROVED** [review]
