### ISSUE TITLE
Compilation warnings multiple targets

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#17227]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [branch](https://github.com/wazuh/wazuh/tree/4.6.0) | - | Any | Sources | Any |

# Description 

As part of https://github.com/wazuh/wazuh/issues/17212 we found that during the compilation process, several warnings are displayed. This issue aims to address those warnings to mitigate bad practices and improve implementation.  

# DoD 

- [ ] Implicit declaration warnings

```sh
unit_tests/wrappers/linux/socket_wrappers.c:86:34: warning: implicit declaration of function ‘wnet_order_big’ [-Wimplicit-function-declaration]
```

- [ ] Redefinitions.

```sh
data_provider/include/sysInfo.h:19: warning: "EXPORTED" redefined
```

- [ ] Arguments overlaping.

```sh
os_execd/exec.c:130:21: warning: ‘snprintf’ argument 4 overlaps destination object ‘exec_cmd’ [-Wrestrict]
```

- [ ] Function definition using fixed size char array.

<details>
<summary>Expand</summary>

```sh
wazuh_db/wdb_integrity.c:456:13: warning: ‘wdbi_update_attempt’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
wazuh_db/wdb_integrity.c:525:5: warning: ‘wdbi_update_completion’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
wazuh_db/wdb_integrity.c:525:5: warning: ‘wdbi_update_completion’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
wazuh_db/wdb_parser.c:4131:13: warning: ‘wdbi_update_attempt’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
wazuh_db/wdb_parser.c:4131:13: warning: ‘wdbi_update_attempt’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
wazuh_db/wdb_parser.c:4152:13: warning: ‘wdbi_update_completion’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
wazuh_db/wdb_parser.c:4152:13: warning: ‘wdbi_update_completion’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
wazuh_db/wdb_parser.c:4232:13: warning: ‘wdbi_update_attempt’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
wazuh_db/wdb_parser.c:4232:13: warning: ‘wdbi_update_attempt’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
wazuh_db/wdb_parser.c:4248:13: warning: ‘wdbi_update_completion’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
wazuh_db/wdb_parser.c:4248:13: warning: ‘wdbi_update_completion’ accessing 41 bytes in a region of size 1 [-Wstringop-overflow=]
```

</details>

- [ ] Unused code

<details>
<summary>Expand</summary>

```sh
unit_tests/wrappers/wazuh/os_crypto/msgs_wrappers.c:30:33: warning: unused parameter ‘keys’ [-Wunused-parameter]
unit_tests/wrappers/wazuh/os_crypto/msgs_wrappers.c:30:59: warning: unused parameter ‘cleartext’ [-Wunused-parameter]
unit_tests/wrappers/wazuh/os_crypto/msgs_wrappers.c:30:74: warning: unused parameter ‘id’ [-Wunused-parameter]
unit_tests/wrappers/wazuh/os_crypto/msgs_wrappers.c:30:91: warning: unused parameter ‘buffer_size’ [-Wunused-parameter]
unit_tests/wrappers/wazuh/os_crypto/msgs_wrappers.c:30:136: warning: unused parameter ‘srcip’ [-Wunused-parameter]
unit_tests/wrappers/wazuh/shared/mq_op_wrappers.c:23:34: warning: unused parameter ‘queue’ [-Wunused-parameter]
/home/vagrant/wazuh/src/syscheckd/src/create_db.c:322:12: warning: unused variable ‘aux’ [-Wunused-variable]
config/global-config.c:160:17: warning: unused variable ‘xml_limits’ [-Wunused-variable]
config/global-config.c:125:31: warning: unused parameter ‘xml’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/rsa_wrappers.c:16:37: warning: unused parameter ‘rsa’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/rsa_wrappers.c:16:46: warning: unused parameter ‘bits’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/rsa_wrappers.c:16:60: warning: unused parameter ‘e_value’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/rsa_wrappers.c:16:79: warning: unused parameter ‘cb’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/pem_wrappers.c:16:39: warning: unused parameter ‘out’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/pem_wrappers.c:17:49: warning: unused parameter ‘x’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/pem_wrappers.c:18:51: warning: unused parameter ‘enc’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/pem_wrappers.c:19:54: warning: unused parameter ‘kstr’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/pem_wrappers.c:20:37: warning: unused parameter ‘klen’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/pem_wrappers.c:21:50: warning: unused parameter ‘cb’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/pem_wrappers.c:22:39: warning: unused parameter ‘u’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/pem_wrappers.c:27:33: warning: unused parameter ‘out’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/pem_wrappers.c:27:50: warning: unused parameter ‘x’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/x509_wrapppers.c:17:28: warning: unused parameter ‘x’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/x509_wrapppers.c:17:41: warning: unused parameter ‘pkey’ [-Wunused-parameter]
unit_tests/wrappers/externals/openssl/x509_wrapppers.c:17:61: warning: unused parameter ‘md’ [-Wunused-parameter]
```

</details>
