### PR TITLE
Support to NPM and PYPI packages in the packages table.

### LINKED ISSUE #5443: Make syscollector capable to fetch the PYPI and node packages from the machine
### Description

This is a feature request from the community (see the discussion [here](https://groups.google.com/u/1/g/wazuh/c/8AQVPhlSDz4)). The user request to make **syscollector** capable to fetch the PYPI and node packages from the machine similar to OSQuery.

In **OSQuery** the npm & python packages are read from package.json and PKG-INFO files. Those files are located in the next directories:

```
/usr/lib/node_modules/npm/package.json

/usr/lib/<Python_Home>/dist-packages/pkg1xxxx.egg-info/PKG-INFO
/usr/lib/<Python_Home1>/dist-packages/pkg2xxxx.egg-info/PKG-INFO
/usr/lib/<Python_Home2>/dist-packages/pkg3xxxx.egg-info/PKG-INFO
```

These files should be read by **syscollector** in order to fetch the mentioned packages.

### PR DESCRIPTION
**Pull request by Dwordcito**
|Related issue|
|---|
|Closes #5443 |

## Description

This PR supports getting, displaying, and synchronizing NPM and PYPI installed packages.

The support is only for the default paths of those packages' installation.

### CODE REVIEW

**Review by GabrielEValenzuela — DISMISSED** [review]
Great job !

File: src/data_provider/src/packages/modernPackageDataRetriever.hpp [hunk 1]
```diff
@@ -0,0 +1,58 @@
+/*
+ * Wazuh SYSINFO
+ * Copyright (C) 2015, Wazuh Inc.
+ * April 16, 2021.
```
Comment (matias-braida) [inline src/data_provider/src/packages/modernPackageDataRetriever.hpp:4]: Update the creation date

File: src/shared_modules/utils/stdFileSystemHelper.hpp [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+#include <string>
+#include <vector>
+
+
+namespace Utils
+{
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wunused-function"
+
+    static void expandAbsolutePath(const std::string& path, std::vector<std::string>& output)
```
Comment (matias-braida) [inline src/shared_modules/utils/stdFileSystemHelper.hpp:27]: A std::deque could be used as output to improve performance

File: src/shared_modules/utils/stringHelper.h [hunk 3]
```diff
@@ -25,6 +25,74 @@
...
+        auto match { true };
+        // Match the glob pattern without regex
+        auto patternPos { 0u };
+
+        for (auto i { 0u }; i < entryName.size(); ++i)
+        {
+            if (patternPos < pattern.size())
+            {
+                // 'x' matches 'x'
+                if (entryName.at(i) == pattern.at(patternPos))
```
Comment (matias-braida) [inline src/shared_modules/utils/stringHelper.h:39]: Wildcard characters "*" and "?" are allowed in the entryName string?
If yes, an escape character should be evaluated to avoid issues in this conditional.

File: src/shared_modules/utils/stdFileSystemHelper.hpp (hunk 2 above)
Comment (matias-braida) [inline src/shared_modules/utils/stdFileSystemHelper.hpp:27]: Maybe, a new parameter with the type of file (REGULAR, DIRECTORY, etc) could be added to reduce useless result entries. Which could result in a performance improvement for later stages.

File: src/data_provider/src/packages/packagesPYPI.hpp [hunk 4]
```diff
@@ -0,0 +1,154 @@
...
+        }
+        void exploreExpandedPaths(const std::vector<std::string>& expandedPaths,
+                                  std::function<void(nlohmann::json&)> callback)
+        {
+            for (const auto& expandedPath : expandedPaths)
+            {
+                try
+                {
+                    // Exist and is a directory
+                    if (TFileSystem::exists(expandedPath) && TFileSystem::is_directory(expandedPath))
```
Comment (matias-braida) [inline src/data_provider/src/packages/packagesPYPI.hpp:116]: If Utils::expandAbsolutePath supports the type of file, then this conditional would be unnecessary, and also the loop cycles will be reduced.

File: src/shared_modules/utils/jsonIO.hpp [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+        static void writeJson(const std::filesystem::path& filePath, const T& json)
+        {
+            std::ofstream file(filePath);
+
+            if (!file.is_open())
+            {
+                throw std::runtime_error("Could not open file");
+            }
+
+            file << json;
```
Comment (matias-braida) [inline src/shared_modules/utils/jsonIO.hpp:59]: Maybe a write error check could be added to throw an exception.

**Review by matias-braida — COMMENTED** [review]
Impressive job!

File: src/data_provider/CMakeLists.txt [hunk 6]
```diff
@@ -14,7 +14,27 @@ if(COVERITY)
   add_definitions(-D__GNUC__=8)
 endif(COVERITY)
 
-set(CMAKE_CXX_FLAGS "-Wall -Wextra -Wshadow -Wnon-virtual-dtor -Woverloaded-virtual -Wunused -Wcast-align -Wformat=2 -std=c++14")
+#Check if filesystem is available
+include(CheckCXXSourceCompiles)
+
+check_cxx_source_compiles("
```
Comment (pereyra-m) [inline src/data_provider/CMakeLists.txt:20]: This doesn't work in my Ubuntu 20.04, with `g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0` inside CMake, but it does manually if c++17 is enabled

```bash
root@ubuntu-focal:/home/vagrant/wazuh# g++ -o test test.cpp 
test.cpp: In function ‘int main()’:
test.cpp:3:14: error: ‘std::filesystem’ has not been declared
    3 |         std::filesystem::path p;
      |              ^~~~~~~~~~
root@ubuntu-focal:/home/vagrant/wazuh# g++ -o test test.cpp -std=c++17
root@ubuntu-focal:/home/vagrant/wazuh# 

```

So in that exploratory test, no `python` packages were obtained.

**Review by pereyra-m — COMMENTED** [review]
Great job with this implementation!

Please, add Github Actions tests for all platforms.

File: src/shared_modules/utils/stdFileSystemHelper.hpp (hunk 2 above)
Comment (Dwordcito) [reply src/shared_modules/utils/stdFileSystemHelper.hpp:27]: the idea is to forget about this from the caller.

File: src/shared_modules/utils/stringHelper.h [hunk 7]
```diff
@@ -25,6 +25,74 @@
 
 namespace Utils
 {
+    static bool patternMatch(const std::string& entryName, const std::string& pattern)
```
[the remark this answers is not in the document]
Comment (Dwordcito) [reply src/shared_modules/utils/stringHelper.h:28]: This is not a regular expression, it's a glob.

https://en.wikipedia.org/wiki/Glob_(programming)

File: src/data_provider/src/sharedDefs.h [hunk 8]
```diff
@@ -106,4 +108,24 @@ enum MacOSArchitecture
...
+};
+
+static const std::set<std::string> UNIX_NPM_DEFAULT_BASE_DIRS
+{
+    "/usr/local/lib",
+    "/opt/homebrew/lib",
+    "/usr/lib",
+    "/home/*/.npm-global/lib",
+    "/Users/*/.npm-global/lib",
+    "/home/*/.nvm/versions/node/v*/lib",
```
Comment (MiguelazoDS) [inline src/data_provider/src/sharedDefs.h:128]: Why isn't this location included as default paths? 
image

File: src/data_provider/src/sharedDefs.h [hunk 9]
```diff
@@ -106,4 +108,24 @@ enum MacOSArchitecture
     ARM64
 };
 
+static const std::set<std::string> UNIX_PYPI_DEFAULT_BASE_DIRS
+{
+    "/usr/lib/python*/*-packages",
+    "/usr/lib64/python*/*-packages",
```
Comment (MiguelazoDS) [inline src/data_provider/src/sharedDefs.h:114]: Although the path is included I can not find this example package
image
image

File: src/data_provider/CMakeLists.txt (hunk 6 above)
Comment (Dwordcito) [reply src/data_provider/CMakeLists.txt:20]: good catch!

**Comment by MiguelazoDS** [comment]
# Exploratory

## Ubuntu Xenial 

Couldn't get information

<details><summary>Show image</summary>

image

</details>

## Ubuntu Jammy 

Sysinfo_test_tool

<details><summary>Show image</summary>

image

</details>

Pip freeze 

<details><summary>Show image</summary>

image

</details>

Diff

<details><summary>Show image</summary>

image

This might be duplicate information
image

</details>

npm list (packages installed with npm install -g)

<details><summary>Show image</summary>

image

</details>

File: src/data_provider/src/sharedDefs.h (hunk 9 above)
Comment (Dwordcito) [reply src/data_provider/src/sharedDefs.h:114]: related to C++ standard definition.

File: src/data_provider/src/sharedDefs.h (hunk 8 above)
Comment (Dwordcito) [reply src/data_provider/src/sharedDefs.h:128]: related to C++ standard definition.

File: src/data_provider/src/packages/packagesPYPI.hpp (hunk 4 above)
Comment (Dwordcito) [reply src/data_provider/src/packages/packagesPYPI.hpp:116]: the idea is only to identify folders in the pypi implementation here.

**Comment by GabrielEValenzuela** [comment]
## Exploratory 

### Debian 12 (bookworm) 🟢 

<details><summary>OS info</summary>

```bash
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

</details>

<details><summary>Instalation of NPM and packages </summary>

```bash
# apt install npm nodejs
```

```bash
# npm install -g json path yaml

# npm list -g
    /usr/local/lib
    ├── json@11.0.0
    ├── path@0.12.7
    └── yaml@2.3.1
```

</details>

<details><summary>Run QA tests </summary>

```bash
# python3 -m pytest -vv qa/
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.11.2, pytest-7.2.1, pluggy-1.0.0+repack -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/vagrant/wazuh/src/data_provider
collected 7 items                                                                                                                                                                                                                            

qa/test_hardware.py::test_json_output PASSED                                                                                                                                                                                           [ 14%]
qa/test_macports.py::test_json_output SKIPPED (test for MacOS only)                                                                                                                                                                    [ 28%]
qa/test_network.py::test_json_output PASSED                                                                                                                                                                                            [ 42%]
qa/test_packages.py::test_json_output PASSED                                                                                                                                                                                           [ 57%]
qa/test_packages.py::test_packages_pypi PASSED                                                                                                                                                                                         [ 71%]
qa/test_packages.py::test_packages_npm PASSED                                                                                                                                                                                          [ 85%]
qa/test_ports.py::test_json_output PASSED 
```
</details>

<details><summary>Running `sys_test_tool` </summary>

```bash
# sysinfo_test_tool --packages | grep "format\"" | sort | uniq -c
      1       "description": "create a trace of your node app per Google's Trace Event format",
    964       "format": "deb",
      3       "format": "npm",
     10       "format": "pypi",
     
# ./sysinfo_test_tool --packages
```

```json
    {
      "architecture": " ",
      "description": " ",
      "format": "pypi",
      "groups": " ",
      "install_time": " ",
      "location": "/usr/lib/python3/dist-packages/soupsieve-2.3.2.dist-info/METADATA",
      "multiarch": " ",
      "name": "soupsieve",
      "priority": " ",
      "size": 0,
      "source": " ",
      "vendor": " ",
      "version": "2.3.2"
    },
    {
      "architecture": " ",
      "description": "JavaScript parser and stringifier for YAML",
      "format": "npm",
      "groups": " ",
      "install_time": " ",
      "location": "/usr/local/lib/node_modules/yaml/package.json",
      "multiarch": " ",
      "name": "yaml",
      "priority": " ",
      "size": 0,
      "source": "https://eemeli.org/yaml/",
      "vendor": " ",
      "version": "2.3.1"
    },
    {
      "architecture": " ",
      "description": "Node.JS path module",
      "format": "npm",
      "groups": " ",
      "install_time": " ",
      "location": "/usr/local/lib/node_modules/path/package.json",
      "multiarch": " ",
      "name": "path",
      "priority": " ",
      "size": 0,
      "source": "http://nodejs.org/docs/latest/api/path.html",
      "vendor": " ",
      "version": "0.12.7"
    },
    {
      "architecture": " ",
      "description": "a 'json' command for massaging and processing JSON on the command line",
      "format": "npm",
      "groups": " ",
      "install_time": " ",
      "location": "/usr/local/lib/node_modules/json/package.json",
      "multiarch": " ",
      "name": "json",
      "priority": " ",
      "size": 0,
      "source": " ",
      "vendor": " ",
      "version": "11.0.0"
    }
```

</details>

**Review by GabrielEValenzuela — APPROVED** [review]
LGTM!

**Review by MiguelazoDS — APPROVED** [review]

**Review by matias-braida — APPROVED** [review]

**Comment by pereyra-m** [comment]
## Exploratory

#### CentOS 9 Stream :green_circle: 

**NPM**

<details><summary>Details</summary>
<p>




</p>
</details> 

**Python**


<details><summary>Details</summary>
<p>

`pip`

```bash
[root@localhost ossec]# pip list
Package              Version
-------------------- --------
chardet              4.0.0
dbus-python          1.2.18
decorator            4.4.2
ethtool              0.14
gpg                  1.15.1
idna                 2.10
iniparse             0.4
libcomps             0.1.18
nftables             0.1
pip                  21.2.3
PyGObject            3.40.1
pyinotify            0.9.6
pyparsing            2.4.7
PySocks              1.7.1
python-dateutil      2.8.1
python-dmidecode     3.12.2
PyYAML               5.4.1
requests             2.25.1
rpm                  4.16.1.3
selinux              3.3
setuptools           53.0.0
six                  1.15.0
subscription-manager 1.29.18
urllib3              1.26.5


```

`agent DB`

```bash
sqlite> SELECT name, version from sys_programs where format = "pypi";
   name = requests
version = 2.25.1

   name = idna
version = 2.10

   name = PySocks
version = 1.7.1

   name = pyparsing
version = 2.4.7

   name = pyinotify
version = 0.9.6

   name = setuptools
version = 53.0.0

   name = gpg
version = 1.15.1

   name = PyGObject
version = 3.40.1

   name = six
version = 1.15.0

   name = chardet
version = 4.0.0

   name = PyYAML
version = 5.4.1

   name = nftables
version = 0.1

   name = rpm
version = 4.16.1.3

   name = python-dmidecode
version = 3.12.2

   name = urllib3
version = 1.26.5

   name = decorator
version = 4.4.2

   name = selinux
version = 3.3

   name = iniparse
version = 0.4

   name = python-dateutil
version = 2.8.1

   name = dbus-python
version = 1.2.18

   name = libcomps
version = 0.1.18

   name = ethtool
version = 0.14

   name = subscription-manager
version = 1.29.18


```

</p>
</details>

**Review by GabrielEValenzuela — APPROVED** [review]

**Review by MiguelazoDS — APPROVED** [review]

**Review by pereyra-m — APPROVED** [review]
LGTM!
