### PR TITLE
Agent alignment to the final manager HTTPS contract

### LINKED ISSUE #38119: Agent alignment to the final manager HTTPS contract: CMAC fields, `/control` payloads, and strict protocol handling
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | wazuh-agentd / HTTPS client / `/control` / AES-CMAC auth | Agent | Sources | Linux / Windows / macOS |

> Part of the agent-side HTTPS migration (#37702, agent epic #37831).
> Focused follow-up to align the agent with the manager's final message/auth protocol definitions.
> Depends on **01** and **02**.

## Description

The manager-side spike introduced updated protocol definitions for AES-CMAC request signing and `/control` request payloads. The agent must support **only the new contract**; no backward-compatibility shim is desired for this development.

Authentication handling also changed: a `401` can mean either an out-of-window `timestamp` or a bad key. In both cases the manager returns its current time in a response header. The agent must retry once with the corrected timestamp delta; if that retry succeeds, it must persist the delta for future requests. If the retry fails again, the failure must be treated as a bad-key signal and escalated to re-enrollment.

Relevant contract sources:

- AES-CMAC auth contract with `timestamp` in the signed canonical request and `Authorization` header.
- `/control` startup request must include `version`.
- `/control` notify request must include `host` metadata.
- Authentication failures return generic `401`, with manager time available in a response header for timestamp correction.
- Request `Content-Type` per endpoint: `application/json` for `/control`, `/config` and `/stats`; deliberately `*/*` for `/stateless`; not JSON at all for `/stateful` and `/download`.

Updated `/control` request bodies:

Startup:

```json
{
  "type": "startup",
  "version": "5.0.0"
}
```

Notify:

```json
{
  "type": "notify",
  "agent": {
    "version": "5.0.0"
  },
  "host": {
    "hostname":     "ubuntu-test",
    "architecture": "x86_64",
    "ip":           "192.168.1.100",
    "os": {
      "name":     "Ubuntu",
      "version":  "20.04",
      "platform": "ubuntu",
      "type":     "linux"
    }
  }
}
```

## Evidence from the current branch (`enhancement/37831-agent-https-client`)

- AES-CMAC `timestamp` signing is already present in `canonicalRequest.cpp` and `cmacSigner.cpp`.
- `/control` startup already sends `version` in `controlStream.cpp`.
- `/control` notify still sends a bare `{"type":"notify"}` in `controlStream.cpp`, so it is not aligned with the current manager contract.
- The legacy C path already knows how to collect/build host metadata (`notify.c`, `start_agent.c`), but that data is not yet wired into the HTTPS client C++ control path.
- `outcomeClassifier.cpp` still carries compatibility branches for old status-code interpretations (`403`, `409`, `426`). For this task we want strict support for the new contract only.
- The current HTTP layer exposes `Retry-After`, but not generic response headers, so the manager-time header needed for the `401` retry flow is not available to the auth logic yet.
- **Every request leaves the agent as `Content-Type: application/x-www-form-urlencoded` while carrying a JSON body.** The client appends only `protocol-version`, `Authorization` (`cmacSigner.cpp`) and an empty `Expect:` (`curlPerformer.cpp`), so libcurl's default for `CURLOPT_POSTFIELDS` goes out untouched. Confirmed across all 27 requests of a live capture (a real agent, all five daemons, against the demo mock over TLS): [#37857 evidence comment](https://github.com/wazuh/wazuh/pull/37857#issuecomment-5136962188).
- The mismatch is with the declared contract, not with running code: `remoted_module` does not inspect `Content-Type` anywhere, and #37732 states the authentication layer is independent of it. Nothing is broken today; the spec and the agent simply disagree.
- The AES-CMAC canonical request covers method, target, agent-id, timestamp and body only (`canonicalRequest.cpp`) — no headers — so setting `Content-Type` cannot affect signing, on either side.

## Goals

- Audit the agent HTTPS client against the final manager-side contract and remove obsolete compatibility assumptions.
- Verify that AES-CMAC signing matches the final canonical definition field-by-field.
- Send the required `version` and `host` data in `/control` requests exactly as specified.
- Recover from clock-skew authentication failures by retrying once with the manager-time delta before escalating to re-enrollment.
- Align status-code handling, mocks, and tests with the new protocol only.

### In scope
- Verify and, where needed, correct AES-CMAC canonical signing fields:
  - `protocol-version`
  - uppercase HTTP method
  - raw request-target
  - `agent-id`
  - `timestamp`
  - exact request body bytes
- Verify `Authorization: Wazuh <agent-id>:<timestamp>:<mac>` generation against the manager contract.
- Capture the manager time response header on `401`, compute the local-vs-server delta, retry once with the adjusted timestamp, and persist the delta on success.
- Escalate to re-enrollment only when the second authentication attempt still fails, treating it as an invalid-key case.
- Ensure `/control` startup sends `type` + `version` exactly as required.
- Ensure `/control` notify sends `type` + `version` + `host` with:
  - `hostname`
  - `architecture`
  - `ip`
  - `os.name`
  - `os.version`
  - `os.platform`
  - `os.type`
- Wire existing agent metadata sources into the HTTPS client control path.
- Remove old compatibility handling where the new contract is already defined as authoritative.
- Review remote-manager HTTP status codes and auth-error semantics against the current contract, and remove outdated local interpretations.
- Send the `Content-Type` each endpoint's contract declares, **per endpoint rather than globally**:
  - `application/json` for `/control`, `/config` and `/stats`.
  - Leave `/stateless` alone: #37732 declares `*/*` deliberately and notes authentication is content-type independent.
  - Do not label `/stateful` or `/download` as JSON; their bodies are not.
- Plumb the type through the request spec rather than setting one header in the performer: the JSON paths use `CURLOPT_POSTFIELDS` while `/stateful` uploads from a spool file (`CURLOPT_UPLOAD`), so a single blanket header would mislabel the non-JSON paths.
- Review the rest of the request/response fields used by the HTTPS client against the latest manager contract and capture any additional drift found during implementation.
- Update unit/component tests, mocks, and documentation comments to match the new contract.

### Out of scope
- Backward compatibility with old interim manager message shapes.
- Unrelated config-schema work (tracked in other issues).
- New manager-side protocol changes beyond the already defined contract.

## Current state on `enhancement/37831-agent-https-client`

- Auth signing already includes `timestamp`, so this issue is not about introducing the field from scratch; it is about validating the full canonical definition and removing legacy compatibility drift.
- Startup already includes `version`.
- Notify payload is still missing the required `host` object.
- Some status-code handling still accepts older protocol interpretations for compatibility.
- The current client still treats `401` as a direct auth failure path; it does not yet perform the manager-time-based retry needed to separate clock skew from a bad key.
- The current HTTP layer does not expose the manager time response header needed for that retry flow.
- No request sets `Content-Type`, so all of them advertise libcurl's form default over a JSON body. This is inert today but contradicts the contract #38023 / #38024 will be built against.
- Existing issue texts in the local stack still reflect an older bare-notify contract, so this issue captures the newer manager-driven adjustment explicitly.

## Tasks

- [ ] Audit AES-CMAC signing end to end against the current manager contract and fix any field/serialization mismatch.
- [ ] Review all signed/request fields used by the client, not just `timestamp`, and confirm they match the final canonical definition.
- [ ] Capture the manager time response header from `401` responses in the HTTP layer and expose it to the auth retry logic.
- [ ] Implement one-shot auth retry with adjusted timestamp delta, and persist that delta when the retry succeeds.
- [ ] Escalate second-attempt auth failure to re-enrollment, treating it as the invalid-key path.
- [ ] Extend the HTTPS `/control` notify payload to include the required `host` metadata.
- [ ] Reuse or adapt the existing metadata-gathering path from the agent C code to feed the HTTPS client control path.
- [ ] Keep `/control` startup aligned with the required `version` field and verify no other stale fields remain.
- [ ] Carry a per-request `Content-Type` through the HTTPS request spec and set `application/json` on `/control`, `/config` and `/stats`, leaving `/stateless`, `/stateful` and `/download` as they are.
- [ ] Assert the header in the component tests: no test currently checks any HTTP header on `/config` or `/stats`, which is why this went unnoticed.
- [ ] Confirm with the manager side whether the endpoints should validate the declared type, or whether the declaration should come out of the spec instead.
- [ ] Review remote error/status codes against the current manager contract and remove obsolete compatibility branches for old protocol/status-code interpretations where the new contract is already settled.
- [ ] Review and adjust tests/mocks (`mock_manager`, unit/component tests) so they validate only the new contract.
- [ ] Update local issue/docs references that still describe the older bare-notify or pre-final auth contract.

## Definition of Done

- The agent signs requests exactly according to the final AES-CMAC contract used by the manager.
- A `401` caused by clock skew is recovered by a single retry using the manager-time delta, and that delta is reused on future requests.
- A repeated `401` after timestamp correction escalates to re-enrollment as the invalid-key path.
- `/control` startup and notify payloads match the final manager-defined JSON shapes.
- Every request advertises the `Content-Type` its endpoint's contract declares, and the non-JSON endpoints are not mislabelled.
- The HTTPS client no longer relies on obsolete compatibility paths for superseded protocol variants.
- Existing tests and mocks validate the new contract only.
- Any additional protocol drift found during the audit is either fixed in this work or explicitly split into follow-up issues.

## References

- #37702
- #37733
- #37733#issuecomment-4996820215
- #37831
- Manager auth docs: `https-events-api.md` / `stateless-api.yaml`
- Code anchors on the current branch:
  - `src/client-agent/https_client/src/canonicalRequest.cpp`
  - `src/client-agent/https_client/src/cmacSigner.cpp`
  - `src/client-agent/https_client/src/controlStream.cpp`
  - `src/client-agent/https_client/src/outcomeClassifier.cpp`
  - `src/client-agent/https_client/src/curlPerformer.cpp` (header assembly; only `Expect:` is added)
  - `src/client-agent/https_client/src/curlHandle.cpp` (`CURLOPT_POSTFIELDS` vs `CURLOPT_UPLOAD`)
  - `src/client-agent/https_client/src/retrySender.cpp` (where the signed headers are attached)
  - `src/client-agent/src/notify.c`
  - `src/client-agent/src/start_agent.c`

### PR DESCRIPTION
**Pull request by Darioortegaleyva**
## Description

This PR aligns the agent-side HTTPS client (`src/client-agent/https_client/`) with the final manager transport/`/control` contract, removing obsolete compatibility assumptions. It audits AES-CMAC signing (already matches, no change), sends the required `host` metadata in `/control` notify, sets the per-endpoint `Content-Type`, recovers from a single `401` with a fresh timestamp before escalating to re-enrollment, and drops the legacy status-code branches (`403`, `426`).

Review fixes: `host.ip` is now sourced from the live connection (`CURLINFO_LOCAL_IP`) instead of the retired `get_agent_ip()`/`getsockname(agt->sock)` path, which is dead on the HTTPS agent (`agt->sock` is permanently `-1`). And `403`/`426` now map to `Retryable` rather than `Permanent`, so an intermediary (reverse proxy, WAF, mTLS gateway) answering those codes no longer causes `/stateless` events to be dropped.

**Proposed Release:** v5.0.0
**Issue:** wazuh/wazuh#38119
**Internal Reference:** agent HTTPS epic wazuh/wazuh#37831 (integrates into `5.0.0-https` via wazuh/wazuh#38012)

## Proposed Changes

- **`/control` notify `host`** - notify now sends `type` + `agent.version` + a `host` block (`hostname`, `architecture`, `ip`, `os.{name,version,platform,type}}`). Added a new `on_collect_host` ABI callback (`include/https_client.h`), threaded a `std::function` into `ControlStream` (`src/controlStream.{hpp,cpp}`, `src/httpsClientFacade.cpp`), and implemented the C collector in `src/client-agent/src/https_client_bridge.c` (fed from `metadata_provider_get()`). Host block is omitted when metadata isn't ready yet.
- **`host.ip` from the live connection** - `hostname`/`architecture`/`os` come from the collector; `host.ip` is a transport fact the module owns, so it is captured via `CURLINFO_LOCAL_IP` (new `ICurlHandle::localIp()` in `curlHandle.cpp`, mirroring `responseCode()`), carried up in `HttpResponse.localIp`, and injected by `ControlStream` on the next notify. The bridge no longer uses the retired `get_agent_ip()`.
- **`403`/`426` are transient, not fatal** - they map to `Retryable` (not `Permanent`), so `/stateless` preserves and retries the batch instead of dropping it when an intermediary returns those codes.
- **Per-endpoint `Content-Type`** - added `HttpRequestSpec.contentType` (`src/httpTypes.hpp`); `CurlPerformer` emits `Content-Type` only when set (`src/curlPerformer.cpp`); `/control` -> `application/json` (`src/controlStream.cpp`). `/stateless` (`*/*`), `/stateful` and `/download` left unset.
- **`401` recovery** - `RetrySender` now retries once immediately with a fresh timestamp on a `401`, and escalates to re-enrollment only if the retry also returns `401` (`src/retrySender.cpp`). This is the contract's retry behavior verbatim (keep body, new timestamp, resign, resend).
- **Strict status codes** - `outcomeClassifier.cpp`: auth is `401` only (`403` is no longer auth); version rejection is `409` only (`426` is the superseded proposal). Both `403` and `426`, being outside the contract, are treated as transient (`Retryable`) so events are not lost. Stale comments updated in `httpTypes.hpp` and `controlStateMachine.hpp`.
- **AES-CMAC audit** - verified the canonical request and headers already match the contract field-by-field; no code change required.
- Tests, mocks (`fakeManager`) and the component suite updated to the new contract, including a new end-to-end `Content-Type` assertion.

### Results and Evidence

Built and validated locally on Linux against the branch's vendored dependencies (`DEPS_VERSION = 99-37361`).

**AES-CMAC canonical matches the contract (wazuh/wazuh#37732) exactly** - `WAZUH-REQUEST\n1\n<UPPER-METHOD>\n<target>\n<agent-id>\n<timestamp>\n<body>`, no trailing LF; `Authorization: Wazuh <id>:<ts>:<mac>`, 32 lowercase hex.

Unit test suite (`https_client_unit_test`):

```bash
$ ./hc_unit
[----------] Global test environment tear-down
[==========] 258 tests from 28 test suites ran.
[  PASSED  ] 258 tests.

# Tests covering this PR's changes:
[ OK ] ControlStreamTest.NotifyCarriesTypeVersionAndHost          # host.ip injected from CURLINFO_LOCAL_IP
[ OK ] ControlStreamTest.NotifyHostOmitsIpWhenLocalIpUnknown
[ OK ] ControlStreamTest.NotifyOmitsHostWhenMetadataUnavailable
[ OK ] CurlPerformerTest.ContentTypeEmittedWhenSet
[ OK ] CurlPerformerTest.NoContentTypeWhenUnset
[ OK ] RetrySenderTest.RepeatedAuthFailureReturnsAuthFail
[ OK ] RetrySenderTest.AuthFailureRecoversWithAFreshTimestamp
[ OK ] RetrySenderTest.AuthGateEscalatesOnlyAfterTheRetryAlsoFails
# OutcomeClassifierTable (parametrized): 403 -> Retryable, 426 -> Retryable, 409 -> VersionRejected
```

Component test suite (`https_client_component_test`, real TLS + libcurl against the fake manager):

```bash
$ ./hc_comp
[==========] 34 tests from 6 test suites ran.
[  PASSED  ] 34 tests.

# End-to-end tests covering this PR's changes:
[ OK ] FacadeE2eTest.ControlRequestsAdvertiseJsonContentType         # /control sends application/json over real curl
[ OK ] FacadeE2eTest.NotifyHostCarriesTheLiveLocalIp (1204 ms)       # notify body received by the manager carries "ip":"127.0.0.1"
[ OK ] FacadeE2eTest.KeyRotationFiresReenrollAndHcSetAgentKeyRecovers   # 401 -> retry -> re-enroll path intact
[ OK ] ComponentTest.VersionRejectionSurfacesAs409
```

Memory safety - unit suite rebuilt with **AddressSanitizer + UndefinedBehaviorSanitizer + LeakSanitizer** and re-run (clean):

```bash
$ ASAN_OPTIONS=detect_leaks=1 ./hc_unit_asan
[==========] 258 tests from 28 test suites ran.
[  PASSED  ] 258 tests.
# exit=0 - no AddressSanitizer/LeakSanitizer errors, no leaks
# (one pre-existing UBSan note in moduleConfig.cpp:78 for an out-of-range verify_mode
#  fed by a validation test - not touched by this PR)
```

The C bridge collector (`bridge_on_collect_host`, not covered by the C++ suites) was exercised against the real `cJSON` + `metadata_provider` under ASan/UBSan/LeakSanitizer, 1000 iterations plus the metadata-unavailable branch:

```bash
$ ASAN_OPTIONS=detect_leaks=1 ./bridge_asan
get rc=0 host=ubuntu-test
last host json: {"hostname":"ubuntu-test","architecture":"x86_64","ip":"192.168.1.100","os":{"name":"Ubuntu","version":"20.04","platform":"ubuntu","type":"linux"}}
no-metadata json: ''        # metadata-not-ready branch: host omitted
# exit=0 - no leaks, no UB, no descriptor issues; output matches the contract shape
```

Diff summary (18 files, +347/-41):

```bash
$ git diff --stat origin/enhancement/37831-agent-https-client...HEAD
 src/client-agent/https_client/include/https_client.h                         |  7 ++
 src/client-agent/https_client/src/controlStateMachine.hpp                    |  2 +-
 src/client-agent/https_client/src/controlStream.cpp                          | 46 +++++++++-
 src/client-agent/https_client/src/controlStream.hpp                          | 11 ++-
 src/client-agent/https_client/src/curlHandle.cpp                             |  7 ++
 src/client-agent/https_client/src/curlPerformer.cpp                          |  6 ++
 src/client-agent/https_client/src/httpTypes.hpp                              |  8 +-
 src/client-agent/https_client/src/httpsClientFacade.cpp                      | 26 ++++++-
 src/client-agent/https_client/src/iCurlHandle.hpp                            |  1 +
 src/client-agent/https_client/src/outcomeClassifier.cpp                      | 20 +++--
 src/client-agent/https_client/src/retrySender.cpp                            | 15 +++-
 src/client-agent/https_client/tests/component/facadeE2e_component_test.cpp   | 63 ++++++++++++++
 src/client-agent/https_client/tests/component/fakeManager.hpp                | 42 +++++++++-
 src/client-agent/https_client/tests/component/httpsClient_component_test.cpp |  4 +-
 src/client-agent/https_client/tests/unit/controlStateMachine_test.cpp        |  4 +-
 src/client-agent/https_client/tests/unit/controlStream_test.cpp              | 86 +++++++++++++++++--
 src/client-agent/https_client/tests/unit/curlPerformer_test.cpp              | 41 +++++++++
 src/client-agent/https_client/tests/unit/mocks/mockCurlHandle.hpp            |  1 +
 src/client-agent/https_client/tests/unit/outcomeClassifier_test.cpp          | 12 +--
 src/client-agent/https_client/tests/unit/retrySender_test.cpp                | 48 ++++++++++--
 src/client-agent/src/https_client_bridge.c                                   | 65 +++++++++++++++
 21 files changed, 473 insertions(+), 42 deletions(-)
```

**Open points (out of this PR's control):**
- The `401` clock-skew *delta* (manager-time response header) described in the issue is **not** present in the accessible contract (the `401` is a bare JSON body, no headers). This PR ships the contract-defined retry (fresh timestamp); the delta/persistence is deferred pending the header name/format from the manager-side `https-events-api.md`.
- The issue says `/download` is "not JSON", but the authoritative `/download` contract (wazuh/wazuh#37733) declares its request body as `application/json`. Left unset per the issue text; needs a manager-side confirmation on which is authoritative.

### Artifacts Affected

- `src/client-agent/https_client/include/https_client.h`
- `src/client-agent/https_client/src/controlStream.cpp` / `controlStream.hpp`
- `src/client-agent/https_client/src/httpsClientFacade.cpp`
- `src/client-agent/https_client/src/curlPerformer.cpp` / `curlHandle.cpp` / `iCurlHandle.hpp`
- `src/client-agent/https_client/src/httpTypes.hpp`
- `src/client-agent/https_client/src/outcomeClassifier.cpp`
- `src/client-agent/https_client/src/retrySender.cpp`
- `src/client-agent/https_client/src/controlStateMachine.hpp`
- `src/client-agent/src/https_client_bridge.c`
- Tests/mocks: `tests/unit/{controlStream,curlPerformer,retrySender,outcomeClassifier,controlStateMachine}_test.cpp`, `tests/unit/mocks/mockCurlHandle.hpp`, `tests/component/{facadeE2e,httpsClient}_component_test.cpp`, `tests/component/fakeManager.hpp`

### Configuration Changes

N/A

### Documentation Updates

N/A

### Tests Introduced

- **Scope:** Unit Tests + Component Tests.
- **Details:** New unit tests for the notify `host` payload (present / omitted / ip-omitted-until-known), the per-endpoint `Content-Type` (emitted/not), the `401` one-shot retry (recovers on fresh timestamp / escalates on repeated `401`), and the status codes (`403`/`426` -> `Retryable`, `409` -> `VersionRejected`). New end-to-end component tests over real TLS + libcurl: `/control` advertises `application/json`, and the notify body received by the manager carries `host.ip` from the live connection. Full suites pass: 258/258 unit, 34/34 component; AddressSanitizer/LeakSanitizer clean.

## Review Checklist

**Manual tests with their corresponding evidence:**

- Compilation without warnings on every supported platform

    - [ ] Linux
    - [ ] Windows
    - [ ] MAC OS X

- [ ] Log syntax and correct language review

- Memory tests for Linux

    - [ ] Coverity
    - [ ] Valgrind (memcheck and descriptor leaks check)
    - [x] AddressSanitizer (unit suite + bridge collector; ASan/UBSan/LeakSanitizer clean)

**General Checklist:**

- [ ] Code changes reviewed
- [ ] Relevant evidence provided
- [ ] Tests cover the new functionality
- [ ] Configuration changes documented (N/A)
- [ ] Developer documentation reflects the changes (code comments updated)
- [ ] Meets requirements and/or definition of done (401 clock-skew delta deferred - see Open points)
- [ ] No unresolved dependencies with other issues (manager-side header + `/download` type to confirm)

### CODE REVIEW

**Comment by Darioortegaleyva** [comment]
### CI status: all 8 failing checks are pre-existing / unrelated to this PR

This PR only touches `src/client-agent/https_client/` and the C bridge. None of the red checks are caused by it (56 pass). Root cause per job:

- **IT Linux/Windows - agentd & enrollment (tier-0-1)** (4 jobs): every case fails at fixture setup with `AttributeError: type object 'RemotedSimulator' has no attribute 'DEFAULT_MERGED_MG_CONTENT'` (`conftest.py:808`). It is a test-framework mismatch, present on the base branch (`enhancement/37831-agent-https-client`, this branch is 0 commits behind it). Being resolved in wazuh/qa-integration-framework#795 and skipped/migrated in #37968 and #38088. A rebase once #37968 lands should turn these green.
- **Unit-Tests (winagent)**: build fails with `undefined reference to hc_submit_sync_session`. The winagent stub `src/unit_tests/client-agent/https_client_stubs.c` does not define that symbol, while `bridge_submit_sync_session` calls it (introduced in c77bfaec8a, 2026-07-29). Pre-existing base-branch break; this PR touches neither the stub nor the sync-session path.
- **check_dll_on_windows**: `test_dll_not_found[wazuh-agent-eventchannel.exe]` flags `Secur32.dll` (DLL-hijacking security test on the eventchannel binary), unrelated to the HTTPS client.
- **Unit-Tests (agent)**: `test_task_registry_ipc_component` (2 subtests) returns `TASK_REGISTRY_RESULT_ERROR` (real-IPC registry unreachable/timeout). Flaky real-IPC component test; this PR does not touch `task_registry`, and `test_https_client_bridge` (which covers the bridge) passes.
- **rtr (client-agent/https_client, agent)**: astyle, cppcheck, build, unit tests and coverage (94.5%) pass. Only the component test `AHeldStatefulRequestDoesNotStallStatelessOrControl` times out on a `startupCount` wait under Valgrind (every op is far slower there). Not modified here, and this change cannot delay the initial startup registration. Passes locally (33/33) without Valgrind.

This PR's own suites are green: 257 unit + 33 component (real TLS) tests, ASan/LeakSanitizer clean. The flaky jobs (`Unit-Tests (agent)`, `rtr`) are being re-run.

File: src/client-agent/src/https_client_bridge.c [hunk 1]
```diff
@@ -1186,6 +1187,74 @@ static void bridge_on_buffer_level(int level, void *user_data)
...
+    }
+
+    if (metadata.hostname[0]) {
+        cJSON_AddStringToObject(host, "hostname", metadata.hostname);
+    }
+    if (metadata.architecture[0]) {
+        cJSON_AddStringToObject(host, "architecture", metadata.architecture);
+    }
+
+    char *agent_ip = get_agent_ip();
```
Comment (MarcelKemp) [inline src/client-agent/src/https_client_bridge.c]: Let’s not use `get_agent_ip()`, as it is a function used for TCP that is due to be deprecated. Let’s look for an alternative by reviewing the current HTTPs code.

**Review by MarcelKemp — CHANGES_REQUESTED** [review]

**Review by MarcelKemp — APPROVED** [review]
There are conflicts to be resolved, but on the whole I approve the PR

**Review by Nicogp — APPROVED** [review]
