### PR TITLE
Update deps version

### LINKED ISSUE #27154: Update CURL dependency to >= 8.11.0
## Description
We could update this dependency since curl reported a fix already available.

CVEs:
- [CVE-2024-9681](https://nvd.nist.gov/vuln/detail/CVE-2024-9681)

### PR DESCRIPTION
**Pull request by GabrielEValenzuela**
|Related issue|
|---|
|Closes #27154 |

# Objective 

This PR aims to increase the deps versioning after updating cURL to 8.11

### CODE REVIEW

**Review by pereyra-m — CHANGES_REQUESTED** [review]
We should fixe the macOS compilation errors

```
ld: Undefined symbols:
  _curl_easy_cleanup, referenced from:
```

**Review by pereyra-m — COMMENTED** [review]
Gj @GabrielEValenzuela 

Please, link an issue or create one for the FIM test that is failing and that's all.
The dependency was uploaded and the tests seem to pass.

**Review by fdalmaup — APPROVED** [review]
LGTM! GJ guys :rocket:
