### ISSUE TITLE
Wazuh 3.13.2 not compiling when Prelude is enabled

### ISSUE THREAD

**Issue by MrRubi** [wazuh/wazuh#6534]
|Wazuh version|Component|Install type|Install method|Platform|
|3.13.2|Prelude|Manager|Sources|Ubuntu 18.04.5 LTS|

I've been working with Wazuh 3.8.2. Last week I upgraded to Wazuh v3.12.3 and it doesn't compile when Prelude is enabled ( I tried with wazuh 3.12.2 but it netiher compile).
I compile and install wazuh from source. Commands used:

```
make clean deps
make clean
make deps
make TARGET=server
```

```
The error I'm getting is:

analysisd/output/prelude.c: In function ‘FileAccess_PreludeLog’:
analysisd/output/prelude.c:236:22: error: invalid operands to binary & (have ‘const char *’ and ‘int’)
             if (perm & S_IWGRP) {
                      ^
analysisd/output/prelude.c:240:22: error: invalid operands to binary & (have ‘const char *’ and ‘int’)
             if (perm & S_IXGRP) {
                      ^
analysisd/output/prelude.c:243:22: error: invalid operands to binary & (have ‘const char *’ and ‘int’)
             if (perm & S_IRGRP ) {
                      ^
analysisd/output/prelude.c:246:22: error: invalid operands to binary & (have ‘const char *’ and ‘int’)
             if (perm & S_ISGID) {
                      ^
analysisd/output/prelude.c:256:18: error: invalid operands to binary & (have ‘const char *’ and ‘int’)
         if (perm & S_IWOTH) {
                  ^
analysisd/output/prelude.c:260:18: error: invalid operands to binary & (have ‘const char *’ and ‘int’)
         if (perm & S_IXOTH) {
                  ^
analysisd/output/prelude.c:263:18: error: invalid operands to binary & (have ‘const char *’ and ‘int’)
         if (perm & S_IROTH ) {
                  ^
analysisd/output/prelude.c: In function ‘OS_PreludeLog’:
analysisd/output/prelude.c:505:35: error: ‘Eventinfo {aka const struct _Eventinfo}’ has no member named ‘md5_after’; did you mean ‘mtime_after’?
                               lf->md5_after,
                                   ^~~~~~~~~
                                   mtime_after
analysisd/output/prelude.c:506:35: error: ‘Eventinfo {aka const struct _Eventinfo}’ has no member named ‘sha1_after’; did you mean ‘sha1_before’?
                               lf->sha1_after,
                                   ^~~~~~~~~~
                                   sha1_before
analysisd/output/prelude.c:507:35: error: ‘Eventinfo {aka const struct _Eventinfo}’ has no member named ‘sha256_after’; did you mean ‘sha256_before’?
                               lf->sha256_after,
                                   ^~~~~~~~~~~~
                                   sha256_before
analysisd/output/prelude.c:508:35: error: ‘Eventinfo {aka const struct _Eventinfo}’ has no member named ‘owner_after’; did you mean ‘owner_before’?
                               lf->owner_after,
                                   ^~~~~~~~~~~
                                   owner_before
analysisd/output/prelude.c:509:35: error: ‘Eventinfo {aka const struct _Eventinfo}’ has no member named ‘gowner_after’; did you mean ‘gowner_before’?
                               lf->gowner_after,
                                   ^~~~~~~~~~~~
                                   gowner_before
analysisd/output/prelude.c:510:35: error: ‘Eventinfo {aka const struct _Eventinfo}’ has no member named ‘perm_after’; did you mean ‘mtime_after’?
                               lf->perm_after);
                                   ^~~~~~~~~~
                                   mtime_after
Makefile:1492: recipe for target 'analysisd/output/prelude.o' failed
make[1]: *** [analysisd/output/prelude.o] Error 1
```

I've been investigating and the last version where Prelude worked was v3.11.5.

Some of the changes apparently detected between those versions are:

On function:

static void FileAccess_PreludeLog(idmef_message_t *idmef,
                           const char *category,
                           const char *filename,
                           const char *md5,
                           const char *sha1,
                           const char *sha256,
                           const char *owner,
                           const char *gowner,
                           const char *perm)

int perm was changed to const char *perm

That seems to be the reason of the first error

`analysisd/output/prelude.c:236:22: error: invalid operands to binary & (have ‘const char *’ and ‘int’)`

Regards
MrRubi

**Comment by pereyra-m** [comment]
Hello @MrRubi !

I was able to compile the sources successfully in the v4.0, because the 3.13 branch hasn't the necessary fix
```
make clean deps
make clean
make deps
make build TARGET=server USE_PRELUDE=y
```

Can you test that version?
Regards.

**Comment by MrRubi** [comment]
Hello,

Yes, It worked for v4.0.

I'll try to upgrade to that version.

Regards

**Comment by pereyra-m** [comment]
Excellent! @MrRubi 

If you are not ready for that version, you could clone the Github repository and select only the commits that fix the Prelude option from the PR [5236](https://github.com/wazuh/wazuh/pull/5236). Then, you would have a custom 3.13.2 version:

```
git clone https://github.com/wazuh/wazuh.git
cd ./master/wazuh/src
git checkout 3.13
git cherry-pick 09bc03a9b680e07432cca4583e94a22561f814ab
git cherry-pick f97a452183a324c7afe93866d9c34100878dccc8
make clean
make deps -j2
make build TARGET=server USE_PRELUDE=y -j2

```

I'm closing this issue, but feel free to open a new one every time you need.
Regards.
