### ISSUE TITLE
[4.0] Error in agent_upgrade binary

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#5394]
Hi team,

Due to recent refactors, both in the API and Framework, the agent_upgrade binary does not work properly. When we try to get the list of outdated agents we get the following error:

```bash
root@wazuh-master:/# /var/ossec/bin/agent_upgrade -l
Internal error: type object 'Agent' has no attribute 'get_outdated_agents'
```

Remediation: Add the import: import wazuh.agent, replace the line 39 and adapt to the new output format of the Framework.
https://github.com/wazuh/wazuh/blob/5e1ebb4e5ca5833a56eacd21244439597824831a/framework/scripts/agent_upgrade.py#L39

Once the bug is fixed, test that the script works correctly with all the changes of 4.0.

Regards

**Comment by AdriiiPRodri** [comment]
## Status update
```bash
root@wazuh-master:/# /var/ossec/bin/agent_upgrade -l
ID    Name                                Version                  
001   wazuh-agent1                        Wazuh v3.13.0            
002   wazuh-agent2                        Wazuh v3.13.0            
003   wazuh-agent3                        Wazuh v3.13.0            
004   wazuh-agent4                        Wazuh v3.13.0            
005   wazuh-agent5                        Wazuh v3.13.0            
006   wazuh-agent6                        Wazuh v3.13.0            
007   wazuh-agent7                        Wazuh v3.13.0            
008   wazuh-agent8                        Wazuh v3.13.0            
009   wazuh-agent9                        Wazuh v3.9.2             
010   wazuh-agent10                       Wazuh v3.9.2             

Total outdated agents: 10
```
