### ISSUE TITLE
4.12.0 does not compile on archlinux with gcc 15.1.1

### ISSUE THREAD

**Issue by krupan** [wazuh/wazuh#29931]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.12.0 | not sure? | Agent | unpacked tarball from github, install.sh | Archlinux  |

When I ran install.sh it tried to compile wazuh source code and I got a bunch of errors.  Here are the first couple:

```
make[2]: Entering directory '/tmp/wazuh-4.12.0/src/shared_modules/dbsync/build'
[ 10%] Building CXX object CMakeFiles/dbsync.dir/src/sqlite/sqlite_wrapper.cpp.o
[ 20%] Building CXX object CMakeFiles/dbsync.dir/src/sqlite/sqlite_dbengine.cpp.o
[ 30%] Building CXX object CMakeFiles/dbsync.dir/src/dbsyncPipelineFactory.cpp.o
[ 50%] Building CXX object CMakeFiles/dbsync.dir/src/dbsync_implementation.cpp.o
[ 50%] Building CXX object CMakeFiles/dbsync.dir/src/dbsync.cpp.o
-- Performing Test HAS_OPTIONAL - Success
-- Performing Test HAS_FILESYSTEM
In file included from /tmp/wazuh-4.12.0/src/shared_modules/dbsync/src/sqlite/sqlite_wrapper.h:15,
                 from /tmp/wazuh-4.12.0/src/shared_modules/dbsync/src/sqlite/sqlite_wrapper.cpp:12:
/tmp/wazuh-4.12.0/src/shared_modules/dbsync/src/sqlite/isqlite_wrapper.h:66:21: error: ‘uint64_t’ does not name a type
   66 |             virtual uint64_t value(const uint64_t&) const = 0;
      |                     ^~~~~~~~
/tmp/wazuh-4.12.0/src/shared_modules/dbsync/src/sqlite/isqlite_wrapper.h:18:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   17 | #include "db_exception.h"
  +++ |+#include <cstdint>
   18 | 
/tmp/wazuh-4.12.0/src/shared_modules/dbsync/src/sqlite/isqlite_wrapper.h:80:58: error: ‘uint64_t’ does not name a type
   80 |             virtual void bind(const int32_t index, const uint64_t value) = 0;
      |                                                          ^~~~~~~~
/tmp/wazuh-4.12.0/src/shared_modules/dbsync/src/sqlite/isqlite_wrapper.h:80:58: note: ‘uint64_t’ is defined in header <cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
/tmp/wazuh-4.12.0/src/shared_modules/dbsync/src/sqlite/isqlite_wrapper.h:80:26: error: ‘virtual void SQLite::IStatement::bind(int32_t, int)’ cannot be overloaded with ‘virtual void SQLite::IStatement::bind(int32_t, int32_t)’
   80 |             virtual void bind(const int32_t index, const uint64_t value) = 0;
      |                          ^~~~
```

**Comment by vikman90** [comment]
Hi @krupan and @MiguelazoDS,

Indeed, the issue you're encountering is due to incompatibility between the Wazuh source code and GCC 15, which is now the default compiler in Arch Linux.

While this is a known issue (#29915), we currently do not have a fix planned, as Arch Linux is not part of our officially supported platforms. However, the Wazuh agent can still be compiled successfully on Arch Linux by using GCC 14 instead.

Here's a workaround you can follow:

```bash
# Install dependencies
pacman -S make gcc14 cmake

# Download and extract Wazuh source code
curl -LO https://github.com/wazuh/wazuh/archive/refs/tags/v4.12.0.tar.gz
tar -zxf v4.12.0.tar.gz

# Build Wazuh agent, define CC and CXX
cd wazuh-4.12.0/src
make TARGET=agent deps
make TARGET=agent CC=gcc-14 CXX=g++-14

# Install Wazuh agent
cd ..
./install.sh
```

As other distributions like Ubuntu or AlmaLinux adopt GCC 15, we plan to address this compatibility issue in a future release.

We appreciate your feedback and thank you again for reporting this!

Best regards.
