### PR TITLE
Extend the coverage for the FIM unit tests

### PR DESCRIPTION
**Pull request by chemamartinez**
## Description

This PR adds new tests to cover more functions and branches of the following files:

- syscheckd/create_db.c

- syscheckd/run_realtime.c

### Previous coverage

image

### New coverage

image

It also fixes a warning related to a static declaration:

```
In file included from /root/wazuh/src/unit_tests/test_wdb_integrity.c:13:0:
/root/wazuh/src/unit_tests/test_wdb_integrity.c: In function ‘test_wdbi_update_completion_wbs_null’:
/root/wazuh/src/unit_tests/test_wdb_integrity.c:374:27: warning: implicit declaration of function ‘wdbi_update_completion’; did you mean ‘wdbi_update_attempt’? [-Wimplicit-function-declaration]
     expect_assert_failure(wdbi_update_completion(NULL, 0, 0));
                           ^
```

### Remaining files to increase coverage

 - syscheckd/config.c

- syscheckd/create_db.c

- syscheckd/fim_sync.c

- syscheckd/syscheck_audit.c

### CODE REVIEW

**Comment by TomasTurina** [comment]
I'm closing this PR since changes have already been introduced in https://github.com/wazuh/wazuh/pull/4577

**Comment by TomasTurina** [comment]
## Update:

image

- 100% of lines covered.
- 76% of branches covered.

**Comment by chemamartinez** [comment]
Closing it due to the FIM development is moved to [3319-fim-rework-sqlite](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite)
