### ISSUE TITLE
Compilation warnings manager target 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#17228]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [branch](https://github.com/wazuh/wazuh/tree/4.6.0) | - | Manager | Sources | Linux |

# Description 

As part of https://github.com/wazuh/wazuh/issues/17212 we found that during the manager compilation process, several warnings are displayed. This issue aims to address those warnings to mitigate bad practices and improve implementation.  

# DoD

## Manager

- [ ] Implicit declaration

```sh
wazuh_modules/vulnerability_detector/wm_vuln_detector.c:34:5: warning: implicit declaration of function ‘mock_assert’ [-Wimplicit-function-declaration]
```

- [ ] Misleading indentation

<details>
<summary>Expand</summary>

```sh
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:897:45: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:896:60: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:901:45: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:901:45: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:901:45: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:901:45: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:901:45: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:901:45: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:901:45: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:901:45: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:897:45: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:896:60: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:899:45: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:897:45: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:896:60: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
wazuh_modules/vulnerability_detector/../vulnerability_detector/wm_vuln_detector.h:899:45: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
```

</details>

- [ ] Parentheses  

```sh
wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c:2528:39: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c:2783:39: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
```

- [ ] Mixed declaration

```sh
analysisd/alerts/getloglocation.c:102:34: warning: argument 2 of type ‘char *’ declared as a pointer [-Warray-parameter=]
```

## Unit Test

- [ ] Review function attributes. 

```sh
/home/vagrant/wazuh/src/unit_tests/analysisd/test_logmsg.c:181:5: warning: format not a string literal and no format arguments [-Wformat-security]
/home/vagrant/wazuh/src/unit_tests/analysisd/test_logmsg.c:193:5: warning: null argument where non-null required (argument 1) [-Wnonnull]
/home/vagrant/wazuh/src/unit_tests/analysisd/test_logmsg.c:199:5: warning: null argument where non-null required (argument 1) [-Wnonnull]
/home/vagrant/wazuh/src/unit_tests/analysisd/test_logmsg.c:205:5: warning: null argument where non-null required (argument 1) [-Wnonnull]
```

- [ ] Type conversion

```sh
/home/vagrant/wazuh/src/unit_tests/os_crypto/md5_sha1_sha256/test_md5_sha1_sha256_op.c:45:17: warning: initialization of ‘FILE *’ {aka ‘struct _IO_FILE *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
```
