### ISSUE TITLE
Update API configuration endpoints for the new VD settings

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#18284]
| Related issues | Branch
|---|---|
|https://github.com/wazuh/wazuh/issues/14153, https://github.com/wazuh/wazuh/issues/17910| [feature/18284-api-vd-adjustments](https://github.com/wazuh/wazuh/tree/feature/18284-api-vd-adjustments) |

## Description
The configuration of the vulnerability detector module is suffering some changes as reported here:
- https://github.com/wazuh/wazuh/issues/17910#issuecomment-1651759662

We need to review and update the API endpoints related to the user configuration file (`ossec.conf`). Changes will probably be limited to the PUT method of the `/manager/configuration` and `/cluster/{node_id}/configuration` endpoints, where it will be necessary to update which configuration values are lists:
https://github.com/wazuh/wazuh/blob/5fa2996c20178a7b70d3866e031273ecd6dfca7c/framework/wazuh/core/configuration.py#L96-L99

In any case, it is necessary to ensure that all related endpoints work correctly after the changes.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by nico-stefani** [comment]
# Issue update

I was reading about the related changes in the VD in order to understand the changes on our side.

**Comment by nico-stefani** [comment]
# Issue Update

I was looking at how to work the mentioned endpoints and removing the `vulnerability-detection` section from the configuration file.  Now isn't necessary because we no longer have multiple `provider` sections.

I need to do some manual testing in order to check the correct function of the endpoints.

**Comment by nico-stefani** [comment]
# Issue Update

I was testing writing the ossec.conf with the proposed structure for `vulnerability-detector` but the changes aren't yet on the core side. So I got the next error.

```json
{
    "data": {
        "affected_items": [],
        "total_affected_items": 0,
        "total_failed_items": 1,
        "failed_items": [
            {
                "error": {
                    "code": 1908,
                    "message": "Error validating configuration: No such tag 'states-indexation' at module 'vulnerability-detector', (1202): Configuration error at 'etc/ossec.conf'.",
                    "remediation": "Please, fix the corrupted files"
                },
                "id": [
                    "manager"
                ]
            }
        ]
    },
    "message": "Could not update configuration",
    "error": 1
}
```

<details><summary>ossec.conf to update</summary>
<p>

```xml
<!--
  Wazuh - Manager - Default configuration for ubuntu 22.04
  More info at: https://documentation.wazuh.com
  Mailing list: https://groups.google.com/forum/#!forum/wazuh
-->
<ossec_config>
    <global>
        <jsonout_output>yes</jsonout_output>
        <alerts_log>yes</alerts_log>
        <logall>no</logall>
        <logall_json>no</logall_json>
        <email_notification>no</email_notification>
        <smtp_server>smtp.example.wazuh.com</smtp_server>
        <email_from>wazuh@example.wazuh.com</email_from>
        <email_to>recipient@example.wazuh.com</email_to>
        <email_maxperhour>12</email_maxperhour>
        <email_log_source>alerts.log</email_log_source>
        <agents_disconnection_time>10m</agents_disconnection_time>
        <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
    </global>
    <alerts>
        <log_alert_level>3</log_alert_level>
        <email_alert_level>12</email_alert_level>
    </alerts>
    <!-- Choose between "plain", "json", or "plain,json" for the format of internal logs -->
    <logging>
        <log_format>plain</log_format>
    </logging>
    <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>tcp</protocol>
        <queue_size>131072</queue_size>
    </remote>
    <!-- Policy monitoring -->
    <rootcheck>
        <disabled>no</disabled>
        <check_files>yes</check_files>
        <check_trojans>yes</check_trojans>
        <check_dev>yes</check_dev>
        <check_sys>yes</check_sys>
        <check_pids>yes</check_pids>
        <check_ports>yes</check_ports>
        <check_if>yes</check_if>
        <!-- Frequency that rootcheck is executed - every 12 hours -->
        <frequency>43200</frequency>
        <rootkit_files>etc/rootcheck/rootkit_files.txt</rootkit_files>
        <rootkit_trojans>etc/rootcheck/rootkit_trojans.txt</rootkit_trojans>
        <skip_nfs>yes</skip_nfs>
    </rootcheck>
    <wodle name="cis-cat">
        <disabled>yes</disabled>
        <timeout>1800</timeout>
        <interval>1d</interval>
        <scan-on-start>yes</scan-on-start>
        <java_path>wodles/java</java_path>
        <ciscat_path>wodles/ciscat</ciscat_path>
    </wodle>
    <!-- Osquery integration -->
    <wodle name="osquery">
        <disabled>yes</disabled>
        <run_daemon>yes</run_daemon>
        <log_path>/var/log/osquery/osqueryd.results.log</log_path>
        <config_path>/etc/osquery/osquery.conf</config_path>
        <add_labels>yes</add_labels>
    </wodle>
    <!-- System inventory -->
    <wodle name="syscollector">
        <disabled>no</disabled>
        <interval>1h</interval>
        <scan_on_start>yes</scan_on_start>
        <hardware>yes</hardware>
        <os>yes</os>
        <network>yes</network>
        <packages>yes</packages>
        <ports all="no">yes</ports>
        <processes>yes</processes>
        <!-- Database synchronization settings -->
        <synchronization>
            <max_eps>10</max_eps>
        </synchronization>
    </wodle>
    <sca>
        <enabled>yes</enabled>
        <scan_on_start>yes</scan_on_start>
        <interval>12h</interval>
        <skip_nfs>yes</skip_nfs>
    </sca>
    <vulnerability-detector>
        <enabled>yes</enabled>
        <states-indexation>yes</states-indexation>
        <feed-interval-update>60m</feed-interval-update>
    </vulnerability-detector>
    <!-- File integrity monitoring -->
    <syscheck>
        <disabled>no</disabled>
        <!-- Frequency that syscheck is executed default every 12 hours -->
        <frequency>43200</frequency>
        <scan_on_start>yes</scan_on_start>
        <!-- Generate alert when new file detected -->
        <alert_new_files>yes</alert_new_files>
        <!-- Don't ignore files that change more than 'frequency' times -->
        <auto_ignore frequency="10" timeframe="3600">no</auto_ignore>
        <!-- Directories to check  (perform all possible verifications) -->
        <directories>/etc,/usr/bin,/usr/sbin</directories>
        <directories>/bin,/sbin,/boot</directories>
        <!-- Files/directories to ignore -->
        <ignore>/etc/mtab</ignore>
        <ignore>/etc/hosts.deny</ignore>
        <ignore>/etc/mail/statistics</ignore>
        <ignore>/etc/random-seed</ignore>
        <ignore>/etc/random.seed</ignore>
        <ignore>/etc/adjtime</ignore>
        <ignore>/etc/httpd/logs</ignore>
        <ignore>/etc/utmpx</ignore>
        <ignore>/etc/wtmpx</ignore>
        <ignore>/etc/cups/certs</ignore>
        <ignore>/etc/dumpdates</ignore>
        <ignore>/etc/svc/volatile</ignore>
        <!-- File types to ignore -->
        <ignore type="sregex">.log$|.swp$</ignore>
        <!-- Check the file, but never compute the diff -->
        <nodiff>/etc/ssl/private.key</nodiff>
        <skip_nfs>yes</skip_nfs>
        <skip_dev>yes</skip_dev>
        <skip_proc>yes</skip_proc>
        <skip_sys>yes</skip_sys>
        <!-- Nice value for Syscheck process -->
        <process_priority>10</process_priority>
        <!-- Maximum output throughput -->
        <max_eps>100</max_eps>
        <!-- Database synchronization settings -->
        <synchronization>
            <enabled>yes</enabled>
            <interval>5m</interval>
            <max_eps>10</max_eps>
        </synchronization>
    </syscheck>
    <!-- Active response -->
    <global>
        <white_list>127.0.0.1</white_list>
        <white_list>^localhost.localdomain$</white_list>
        <white_list>127.0.0.53</white_list>
    </global>
    <command>
        <name>disable-account</name>
        <executable>disable-account</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>restart-wazuh</name>
        <executable>restart-wazuh</executable>
    </command>
    <command>
        <name>firewall-drop</name>
        <executable>firewall-drop</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>host-deny</name>
        <executable>host-deny</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>route-null</name>
        <executable>route-null</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>win_route-null</name>
        <executable>route-null.exe</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <command>
        <name>netsh</name>
        <executable>netsh.exe</executable>
        <timeout_allowed>yes</timeout_allowed>
    </command>
    <!--
  <active-response>
    active-response options here
  </active-response>
  -->
    <!-- Log analysis -->
    <localfile>
        <log_format>syslog</log_format>
        <location>/var/ossec/logs/active-responses.log</location>
    </localfile>
    <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/auth.log</location>
    </localfile>
    <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/syslog</location>
    </localfile>
    <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/dpkg.log</location>
    </localfile>
    <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/kern.log</location>
    </localfile>
    <localfile>
        <log_format>command</log_format>
        <command>df -P</command>
        <frequency>360</frequency>
    </localfile>
    <localfile>
        <log_format>full_command</log_format>
        <command>netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d</command>
        <alias>netstat listening ports</alias>
        <frequency>360</frequency>
    </localfile>
    <localfile>
        <log_format>full_command</log_format>
        <command>last -n 20</command>
        <frequency>360</frequency>
    </localfile>
    <ruleset>
        <!-- Default ruleset -->
        <decoder_dir>ruleset/decoders</decoder_dir>
        <rule_dir>ruleset/rules</rule_dir>
        <rule_exclude>0215-policy_rules.xml</rule_exclude>
        <list>etc/lists/audit-keys</list>
        <list>etc/lists/amazon/aws-eventnames</list>
        <list>etc/lists/security-eventchannel</list>
        <!-- User-defined ruleset -->
        <decoder_dir>etc/decoders</decoder_dir>
        <rule_dir>etc/rules</rule_dir>
    </ruleset>
    <rule_test>
        <enabled>yes</enabled>
        <threads>1</threads>
        <max_sessions>64</max_sessions>
        <session_timeout>15m</session_timeout>
    </rule_test>
    <!-- Configuration for wazuh-authd -->
    <auth>
        <disabled>no</disabled>
        <port>1515</port>
        <use_source_ip>no</use_source_ip>
        <purge>yes</purge>
        <use_password>no</use_password>
        <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
        <!-- <ssl_agent_ca></ssl_agent_ca> -->
        <ssl_verify_host>no</ssl_verify_host>
        <ssl_manager_cert>etc/sslmanager.cert</ssl_manager_cert>
        <ssl_manager_key>etc/sslmanager.key</ssl_manager_key>
        <ssl_auto_negotiate>no</ssl_auto_negotiate>
    </auth>
    <cluster>
        <name>wazuh</name>
        <node_name>node01</node_name>
        <node_type>master</node_type>
        <key></key>
        <port>1516</port>
        <bind_addr>0.0.0.0</bind_addr>
        <nodes>
            <node>NODE_IP</node>
        </nodes>
        <hidden>no</hidden>
        <disabled>yes</disabled>
    </cluster>
</ossec_config>
```

</p>
</details>

I will block the issue until the changes were applied.

**Comment by nico-stefani** [comment]
# Update

I was resuming with this and seeing if the changes were applied by the core team.

Still, I'm getting this error

```
root@wazuh-master:/var/ossec# bin/wazuh-control restart
2023/10/23 20:21:02 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'vulnerability-detection'.
2023/10/23 20:21:02 wazuh-csyslogd: ERROR: (1202): Configuration error at 'etc/ossec.conf'.
2023/10/23 20:21:02 wazuh-csyslogd: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
wazuh-csyslogd: Configuration error. Exiting
```

I need to investigate more deeply and check my environment.

**Comment by nico-stefani** [comment]
# Update

I was trying to apply the configuration in the `ossec.conf` directly, but now I'm getting an error with modulesd that doesn't allow me to continue with the API flow.

* Used Configuration

```xml
<ossec_config>
    <indexer>
        <enabled>yes</enabled>
        <hosts>
            <host>http://10.2.20.2:9200/</host>
        </hosts>

        <username>user</username>
        <password>pwd</password>
        <api_key>asasdasd</api_key>
    </indexer>

    <vulnerability-detection>
        <enabled>yes</enabled>
        <states-indexation>yes</states-indexation>
        <feed-interval-update>300s</feed-interval-update>
    </vulnerability-detection>
</ossec_config>
```

```
Wazuh v4.8.0 Stopped
Starting Wazuh v4.8.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2023/10/24 16:57:00 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
2023/10/24 16:57:06 wazuh-modulesd:router: INFO: Loaded router module.
2023/10/24 16:57:06 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
wazuh-modulesd: Process 17905 not used by Wazuh, removing...
wazuh-modulesd did not start correctly.
```

@Dwordcito any suggestion to apply the correct configuration? I'm working with the [dev-14153-vulndet-refactor](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor) branch.

**Comment by nico-stefani** [comment]
# Update

With the last changes made, I cannot build the manager to continue with the tests

```
make TARGET=server -C src
...
[ 92%] Building CXX object wazuh_modules/vulnerability_scanner/src/scanOrchestrator/CMakeFiles/scan_orchestrator.dir/scanOrchestrator.cpp.o
[ 93%] Linking CXX static library libscan_orchestrator.a
make[4]: Leaving directory '/wazuh/src/build'
[ 93%] Built target scan_orchestrator
make[4]: Entering directory '/wazuh/src/build'
make[4]: Leaving directory '/wazuh/src/build'
make[4]: Entering directory '/wazuh/src/build'
[ 95%] Building CXX object wazuh_modules/vulnerability_scanner/CMakeFiles/vulnerability_scanner.dir/src/vulnerabilityScanner.cpp.o
[ 96%] Building CXX object wazuh_modules/vulnerability_scanner/CMakeFiles/vulnerability_scanner.dir/src/vulnerabilityScannerFacade.cpp.o
/wazuh/src/wazuh_modules/vulnerability_scanner/src/vulnerabilityScannerFacade.cpp:13:10: fatal error: flatbuffers/include/syscollector_deltas_generated.h: No such file or directory
   13 | #include "flatbuffers/include/syscollector_deltas_generated.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [wazuh_modules/vulnerability_scanner/CMakeFiles/vulnerability_scanner.dir/build.make:90: wazuh_modules/vulnerability_scanner/CMakeFiles/vulnerability_scanner.dir/src/vulnerabilityScannerFacade.cpp.o] Error 1
make[4]: Leaving directory '/wazuh/src/build'
make[3]: *** [CMakeFiles/Makefile2:853: wazuh_modules/vulnerability_scanner/CMakeFiles/vulnerability_scanner.dir/all] Error 2
make[3]: Leaving directory '/wazuh/src/build'
make[2]: *** [Makefile:146: all] Error 2
make[2]: Leaving directory '/wazuh/src/build'
make[1]: *** [Makefile:1754: build_wazuh_cmake] Error 2
make[1]: Leaving directory '/wazuh/src'
make: *** [Makefile:812: server] Error 2
make: Leaving directory '/wazuh/src'
```

**Comment by nico-stefani** [comment]
# Update

Finally, I can start the environment. So, I started making the changes to adapt the API endpoint.

**Comment by nico-stefani** [comment]
# Update

Trying to execute the AIT I found an error building on Ubuntu 20.04 OS.

```
47.1 [ 88%] Linking CXX executable indexer_connector_tool
147.4 make[4]: Leaving directory '/wazuh/src/build'
147.4 [ 88%] Built target indexer_connector_tool
147.9 [ 90%] Linking CXX executable utils_unit_test
149.0 make[4]: Leaving directory '/wazuh/src/build'
149.0 [ 90%] Built target utils_unit_test
149.1 [ 91%] Linking CXX shared library libcontent_manager.so
149.7 make[4]: Leaving directory '/wazuh/src/build'
149.7 [ 91%] Built target content_manager
149.7 make[4]: Entering directory '/wazuh/src/build'
149.7 make[4]: Entering directory '/wazuh/src/build'
149.7 Scanning dependencies of target content_manager_test_tool
149.7 make[4]: Leaving directory '/wazuh/src/build'
149.8 make[4]: Entering directory '/wazuh/src/build'
149.8 [ 92%] Building CXX object shared_modules/content_manager/testtool/CMakeFiles/content_manager_test_tool.dir/main.cpp.o
149.8 Scanning dependencies of target vulnerability_scanner
149.8 make[4]: Leaving directory '/wazuh/src/build'
149.8 make[4]: Entering directory '/wazuh/src/build'
149.8 [ 95%] Building CXX object wazuh_modules/vulnerability_scanner/CMakeFiles/vulnerability_scanner.dir/src/vulnerabilityScannerFacade.cpp.o
149.8 [ 95%] Building CXX object wazuh_modules/vulnerability_scanner/CMakeFiles/vulnerability_scanner.dir/src/vulnerabilityScanner.cpp.o
151.9 [ 96%] Linking CXX executable content_manager_test_tool
152.1 /usr/bin/ld: /wazuh/src/external/lzma/build/liblzma.a(stream_decoder_mt.c.o): undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'
152.1 /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
152.1 collect2: error: ld returned 1 exit status
152.1 make[4]: *** [shared_modules/content_manager/testtool/CMakeFiles/content_manager_test_tool.dir/build.make:87: shared_modules/content_manager/testtool/content_manager_test_tool] Error 1
152.1 make[4]: Leaving directory '/wazuh/src/build'
152.1 make[3]: *** [CMakeFiles/Makefile2:781: shared_modules/content_manager/testtool/CMakeFiles/content_manager_test_tool.dir/all] Error 2
152.1 make[3]: *** Waiting for unfinished jobs....
155.2 [ 97%] Linking CXX shared library libvulnerability_scanner.so
155.5 make[4]: Leaving directory '/wazuh/src/build'
155.5 [ 97%] Built target vulnerability_scanner
155.5 make[3]: Leaving directory '/wazuh/src/build'
155.5 make[2]: Leaving directory '/wazuh/src/build'
155.5 make[2]: *** [Makefile:141: all] Error 2
155.5 make[1]: *** [Makefile:1754: build_wazuh_cmake] Error 2
155.5 make[1]: Leaving directory '/wazuh/src'
155.5 make: *** [Makefile:812: server] Error 2
155.5
155.5  Error 0x5.
155.5  Building error. Unable to finish the installation.
------
failed to solve: process "/bin/sh -c /wazuh/install.sh" did not complete successfully: exit code: 1
```

Previously I was working on an Ubuntu 22.04 image and the build worked without problems.

**Comment by nico-stefani** [comment]
# Update

The core team is working on a solution for the build error in #19964

**Comment by nico-stefani** [comment]
# Update

I was checking the AIT in:

* api/test/integration/test_cluster_endpoints.tavern.yaml
* api/test/integration/test_manager_endpoints.tavern.yaml
* api/test/integration/test_rbac_black_cluster_endpoints.tavern.yaml
* api/test/integration/test_rbac_white_cluster_endpoints.tavern.yaml

I need to check if there any other tests to fix.
