### ISSUE TITLE
Wazuh DB state unit tests failed 

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#19138]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.6.0-dev | Unit tests| Manager |

```
[==========] Running 1 test(s).
[ RUN      ] test_wazuhdb_create_state_json
[  ERROR   ] --- 0x658c != 0x658a
[   LINE   ] --- /root/wazuh/src/unit_tests/wazuh_db/test_wazuh_db_state.c:513: error: Failure!
[  FAILED  ] test_wazuhdb_create_state_json
[==========] Running 1 test(s).
[ RUN      ] test_wazuhdb_create_state_json
[  ERROR   ] --- 0x47f9 != 0x47f8
[   LINE   ] --- /root/wazuh/src/unit_tests/wazuh_db/test_wazuh_db_state.c:518: error: Failure!
[  FAILED  ] test_wazuhdb_create_state_json
[  ERROR   ] --- 0xdf != 0xde
[   LINE   ] --- /root/wazuh/src/unit_tests/wazuh_db/test_wazuh_db_state.c:548: error: Failure!
[  FAILED  ] test_wazuhdb_create_state_json
```

This issue seems to be caused by PR #19073, whose checks did not include the CMocka unit tests due to an unknown reason.
