### ISSUE TITLE
Investigate Python 3.10 breaking changes

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#13365]
With the new Python 3.10 release, there are internal changes that affect us directly. In this issue we will investigate the implications of upgrading to 3.10 from 3.9. We will list all the necessary changes to our code as well as necessary changes to our dependency versions.

An example of a breaking change is as follows:

```
framework/wazuh/core/cluster/tests/test_local_client.py:7: in <module>
    from collections import Callable
E   ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

In Python 3.10 to import `Callable` it is necessary to do it from `abc`:

```
from collections.abc import Callable
```

Therefore the purpose of this issue is only to list the problems and the solution to them. In case we need to update dependency versions, the version of the dependency that works with Python 3.10 and higher will be indicated.

**Comment by AdriiiPRodri** [comment]
## Status update

After running all the unit tests, we have verified that the only existing problem is related to the import `from collections import Callable`, this should be modified as indicated in the issue description:
```
from collections.abc import Callable
```

**Comment by fdalmaup** [comment]
# Issue Update

When executing the integration tests (see https://github.com/wazuh/wazuh/issues/13373#issuecomment-1353735154), the following error message was found in the `cluster.log` file:
```
ERROR: [Master] [Local agent-groups] Error getting agent-groups from WDB: _UnixSelectorEventLoop.create_unix_connection() got an unexpected keyword argument 'loop'
```

Reviewing the [release's What's new section](https://docs.python.org/3.10/whatsnew/3.10.html), the error's reason was confirmed:
```
The loop parameter has been removed from most of asyncio‘s high-level API following deprecation in Python 3.8.
```

The asyncio high-level API is used all over the framework module, but the mentioned error is directly related to the following code section:
https://github.com/wazuh/wazuh/blob/8583032cda7477b137ebe766e948dbcd651162cc/framework/wazuh/core/wdb.py#L40-L42

More information about the new implementation of `open_connection(...)` is in this [documentation link](https://docs.python.org/3.10/library/asyncio-stream.html#asyncio.open_connection).

We should review the usage of the `loop` parameter in every function that uses asyncio‘s high-level API.

**Comment by mhamra** [comment]
### ISSUE UPDATE

In Python 3.10.11, the function open_unix_connection calls events.._get_event_loop() at the very start of the function code, so the parameter is not required anymore and it doesn't exist in the function signature.

The loop parameter was deleted from the wazuh code in pr [#16408](https://github.com/wazuh/wazuh/pull/16408)

**Comment by fdalmaup** [comment]
# Issue Update

After the [latest v3.10.11](https://github.com/wazuh/wazuh/issues/13265#issuecomment-1526204671) update of the Wazuh embedded interpreter and checking the [version Changelog](https://docs.python.org/3.10/whatsnew/changelog.html#python-3-10-11-final), no breaking changes were found. 

The issue is returned to the backlog until the final version of the embedded Python interpreter is established and the team starts the process to include it definitively in the production dependencies.

**Comment by dpetiz** [comment]
Any update about it?

**Comment by fdalmaup** [comment]
# Issue Update

Hi @dpetiz. Sorry for the delay. Currently, we are in the [final testing phase](https://github.com/wazuh/wazuh/issues/13373#issuecomment-1791588059) to add the embedded interpreter in `4.8.0`. Once every test passes, if no other necessary change is needed, the team will merge #20003.

**Comment by dpetiz** [comment]
Thank you guys, i hope it could be released soon.
Good job!

**Comment by fdalmaup** [comment]
# Issue Summary

After every available test has been carried out in #13373 and no other necessary change was encountered, we could summarize the found Python 3.10 and related dependencies breaking changes that required modifications in our code:
- `Collections` is now imported via `collections.abc` (more info [here](https://docs.python.org/3.10/whatsnew/3.10.html#collections-abc))
- The loop parameter has been [removed](https://docs.python.org/3.10/whatsnew/3.10.html#removed) from most of [asyncio](https://docs.python.org/3.10/library/asyncio.html#module-asyncio)‘s [high-level API](https://docs.python.org/3.10/library/asyncio-api-index.html) following deprecation in Python 3.8.
- The update on the `cryptography` dependency from `3.3.2` to `41.0.4` required a thorough analysis. It modified its internal implementation, which is taken into account for Wazuh Framework tests, and required the changes mentioned [here](https://github.com/wazuh/wazuh/issues/13267#issuecomment-1560133875).

This issue is ready to be cross-reviewed and later closed.

**Comment by nico-stefani** [comment]
LGTM
