### ISSUE TITLE
RTR build.py tool does not work with modern lcov versions

### ISSUE THREAD

**Issue by Miguevrgo** [wazuh/wazuh#34236]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.14.4 | CI | Manager | Sources | Ubuntu 24.04 |

## Description

The build system and CI scripts (build.py, run_check.py) fail when running on Ubuntu 24.04 LTS. These same commands work correctly on Ubuntu 22.04 LTS.

The failures are caused by newer versions of the development toolchain included in Ubuntu 24.04, specifically:
- Cppcheck (2.13+): Scans the build/ directory recursively and fails on temporary CMake compiler check files.
- LCOV (2.0+): Changed its output format (removed dots ......), breaking the regex parser in run_check.py.

## Steps to reproduce
On an Ubuntu 24.04 environment follow general build script instrutions for TARGET=server and run a module build, for example:
```sh
python3 build.py -r shared_modules/dbsync --cpus 4
```

## Result
The build fails at different stages.
#### Cppcheck Failure
Cppcheck analyzes Cmake temporary files inside the `build` directory treating compiler macros as syntax errors.
```sh
/home/vagrant/wazuh/src/wazuh_modules/syscollector/build/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c:757:28: error: syntax error [syntaxError]
char const* info_version = "INFO" ":" "compiler_version[" COMPILER_VERSION "]";
```
#### Coverage/LCOV Failure
After fixing the previous failure, the coverage check crashes python because the regex expects the old LCOV format (which uses '.' instead of spaces). The current regexp matching in `ci/run_check.py:checkCoverage` is strict and fails with this new format:
```sh
ValueError: could not convert string to float: ''
```
