### PR TITLE
Fix gcloud: defer bucket/pubsub imports to isolate broken deps

### LINKED ISSUE #38847: A broken storage`dependency disables the GCP Pub/Sub path too
## Description

`wodles/gcloud/gcloud.py` imports both integration backends at module scope, before it has parsed its arguments and therefore before it knows which one the user asked for:

```python
from buckets.access_logs import GCSAccessLogs
from pubsub.subscriber import WazuhGCloudSubscriber
```

`buckets.access_logs` pulls in `buckets/bucket.py`, which imports `google-cloud-storage`. If that import fails for any reason, the module never finishes loading and `gcloud` exits — even when it was invoked as `-T pubsub` and would not have touched Cloud Storage at all.

This turns a single broken dependency into a **complete** GCP outage instead of a partial one. It is what happened in the beta5 run: `google-cloud-pubsub` imported perfectly well on the agent's Python 3.14, but `gcp-pubsub` still failed on every cycle, purely because the bucket import on the line above ran first.

## Environment

- **Wazuh:** 5.0.0-beta5 (`wodles/gcloud` byte-identical to `v5.0.0-beta4`)
- **Affected component:** agent — `wodles/gcloud`
- Independent of OS, architecture and Python version.

## Steps to reproduce

1. Prepare an environment where `google-cloud-pubsub` imports correctly but `google-cloud-storage` does not (for example Python >= 3.13 with `google-cloud-storage==1.39.0`, or simply uninstall `google-cloud-storage`):

   ```bash
   python3 -c "from google.cloud import pubsub_v1"   # succeeds
   python3 -c "from google.cloud import storage"     # fails
   ```

2. Run the wodle in **Pub/Sub** mode only:

   ```bash
   /var/ossec/wodles/gcloud/gcloud -T pubsub -p <PROJECT> -s <SUBSCRIPTION> \
     -c /var/ossec/wodles/gcloud/gcp.json -m 100 -t 1 ; echo "rc=$?"
   ```

## Expected result

The Pub/Sub integration runs normally: it has every dependency it needs, and Cloud Storage is irrelevant to the requested integration type. A bucket-side dependency problem should degrade only the bucket integration.

## Actual result

The wodle exits non-zero without pulling a single message, with a traceback originating in `buckets/bucket.py`. In `ossec.log` the operator sees only:

```
wazuh-modulesd:gcp-pubsub: INFO: Module started.
wazuh-modulesd:gcp-pubsub: WARNING: Command returned exit code 1
```

repeated once per polling interval, with no indication that the failure comes from an unrelated backend.

## Evidence

[agent_e2e-linux-agent.log](https://github.com/user-attachments/files/31780055/agent_e2e-linux-agent.log)

[commands.json](https://github.com/user-attachments/files/31780077/commands.json)

[manager_e2e-aio-node.log](https://github.com/user-attachments/files/31780099/manager_e2e-aio-node.log)

### PR DESCRIPTION
**Pull request by MAnDumu**
## Description

`wodles/gcloud/gcloud.py` imported both integration backends (`GCSAccessLogs` from `buckets.access_logs`, `WazuhGCloudSubscriber` from `pubsub.subscriber`) at module scope, before parsing arguments. `buckets.access_logs` transitively imports `buckets/bucket.py`, which does a guarded import of `google-cloud-storage`. If that import failed for any reason, the whole `gcloud.py` module failed to load — taking down the Pub/Sub path with it even when the wodle was invoked with `-T pubsub` and never touched Cloud Storage at all.

Closes #38847

**Retargeted to `4.14.9`**: this PR originally targeted `main`; it now targets the `4.14.9` maintenance branch instead, ported from the (still open, unmerged) `main` version. `wodles/gcloud/gcloud.py` is byte-identical between the two branches, so the fix itself ported unchanged. `wodles/gcloud/tests/test_gcloud.py` differs: `4.14.9`'s baseline doesn't have the `test_main_block_invokes_main` test (added on `main` by an unrelated, later commit), so the port doesn't touch it — the genuinely new test for this fix (`test_gcloud_pubsub_unaffected_by_broken_bucket_import`) is unaffected by that difference and already exercises the same `runpy`-as-`__main__` invocation path.

## Proposed Changes

- Moved both imports out of module scope and into the specific branch of `main()` that actually needs them: `WazuhGCloudSubscriber` is imported only inside the `pubsub` branch, `GCSAccessLogs` only inside the `access_logs` branch. Both imports now happen inside the existing `try` block in `main()`, which already catches `WazuhIntegrationException`/`GCloudError` and logs through the wodle's real logger before exiting with the corresponding error code — so a dependency failure on the requested integration is now reported cleanly instead of crashing at import time with an unhandled traceback.
- Updated `wodles/gcloud/tests/test_gcloud.py`: tests that patched `gcloud.GCSAccessLogs` / `gcloud.WazuhGCloudSubscriber` (relying on those names existing as module-level attributes, which is no longer the case with deferred imports) now patch the real source instead (`buckets.access_logs.GCSAccessLogs` / `pubsub.subscriber.WazuhGCloudSubscriber`), matching the pattern `test_gcloud_ko` already used.
- No changes to `buckets/bucket.py`, `pubsub/subscriber.py` or `exceptions.py` — a related but separate defect in `buckets/bucket.py`'s own guarded-import error handling was already fixed independently on this branch by #38856.

### Results and Evidence

Full `wodles/gcloud/tests/` suite passes on `4.14.9`'s actual tree: 74/74 (Python 3.10, the interpreter this branch's CI uses for wodles).

To confirm the new test actually catches a regression (not just passes trivially), the fix was temporarily reverted in isolation (`gcloud.py` only) and the new test re-run:

```
tests/test_gcloud.py::test_gcloud_pubsub_unaffected_by_broken_bucket_import FAILED
gcloud.py:15: in <module>
    from buckets.access_logs import GCSAccessLogs
ModuleNotFoundError: import of buckets.access_logs halted; None in sys.modules
```

With the fix restored, the same test passes and the full suite is green again.

### Manual tests with their corresponding evidence

N/A — pure Python change in an agent wodle, no C compilation involved (no manager/agent/winagent binaries affected, no memory/leak tooling applies). Checklist left below unchecked as it doesn't apply to this change.

- Compilation without warnings on every supported platform
  - [ ] Linux
  - [ ] Windows 
  - [ ] MAC OS X
- [ ] Log syntax and correct language review

- Memory tests for Linux
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Coverity
  - [ ] UMDH
- Memory tests for macOS
  - [ ] Leaks
  - [ ] AddressSanitizer

- Decoder/Rule tests _(Wazuh v4.x)_
  - [ ] Added unit testing files ".ini"
  - [ ] `runtests.py` executed without errors

- Engine _(Wazuh v5.x and above)_
  - [ ] Test run in parallel
  - [ ] ASAN for test (utest/ctest)
  - [ ] TSAN for test and wazuh-engine.

- Wazuh server API/Framework
  - [ ] Run API Integration Tests

### Artifacts Affected

- `wodles/gcloud/gcloud.py` (agent wodle script, shipped as-is, no compiled artifact).

### Configuration Changes

N/A

### Tests Introduced

- `test_gcloud_pubsub_unaffected_by_broken_bucket_import` (`wodles/gcloud/tests/test_gcloud.py`): runs `gcloud.py` fresh via `runpy.run_path` with `sys.modules['buckets.access_logs']` poisoned to `None`, and asserts a `pubsub` run still exits `0` — reproducing the exact scenario in #38847. Verified it fails against the pre-fix code (see Results and Evidence above).

## Review Checklist

- [x] Code changes reviewed — independent review by `code-config-reviewer` (Approved) and cross-check by `contrarian-reviewer` (partial disagreement, resolved: the finding is a pre-existing, separate defect already covered by #38846 / PR #38856, out of scope here). The retarget to `4.14.9` itself was reviewed again by both after porting.
- [x] Tests cover the new functionality
- [ ] Relevant evidence provided
- [ ] Configuration changes documented
- [ ] Developer documentation reflects the changes
- [ ] Meets requirements and/or definition of done
- [ ] No unresolved dependencies with other issues
- [ ] ...

### CODE REVIEW

**Comment by MAnDumu** [comment]
Reproduced the steps to reproduce from #38847 end-to-end in an isolated venv (`google-cloud-pubsub==2.21.5` installed, `google-cloud-storage` absent — same effect as the Python >= 3.13 case):

```
python3 -c "from google.cloud import pubsub_v1"   # succeeds
python3 -c "from google.cloud import storage"      # ImportError: cannot import name 'storage' from 'google.cloud'
```

**Before this fix (`main`)** — `gcloud -T pubsub ...` never runs any pubsub code at all:

```
Traceback (most recent call last):
  File ".../buckets/bucket.py", line 23, in <module>
    from google.cloud import storage
ImportError: cannot import name 'storage' from 'google.cloud' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../gcloud.py", line 15, in <module>
    from buckets.access_logs import GCSAccessLogs
  File ".../buckets/access_logs.py", line 15, in <module>
    from bucket import WazuhGCloudBucket
  File ".../buckets/bucket.py", line 27, in <module>
    raise exceptions.WazuhIntegrationException(errcode=1003, package=e.name)
  File ".../exceptions.py", line 28, in __init__
    info = self.__class__.ERRORS[errcode]
AttributeError: type object 'WazuhIntegrationException' has no attribute 'ERRORS'
rc=1
```

That `AttributeError` is a separate, pre-existing defect in `buckets/bucket.py`'s guarded import (already covered by #38846 / #38856) — not introduced by this fix, but it's what actually surfaces here once the storage import fails, on top of everything in #38847's description.

**After this fix**, same venv, same command — pubsub runs normally and only fails later, on the (deliberately invalid) dummy credentials file, never touching the bucket code path:

```
:gcloud_wodle: - INFO - Working with Google Cloud Pub/Sub
:gcloud_wodle: - DEBUG - Setting 1 thread to pull 100 messages in total
:gcloud_wodle: - CRITICAL - Unknown error: Service account info was not in the expected format, missing fields token_uri, client_email.
...
rc=231
```

Confirms this resolves #38847 end-to-end, not just at the unit-test level.

**Review by jpcerrone — APPROVED** [review]
LGTM

**Review by cborla — APPROVED** [review]
LGTM
